In [1]:
from PIL import Image
import numpy as np
import sys
import os
import csv

In [2]:
def createFileList(myDir, format='.jpg'):
    fileList = []
    print(myDir)
    for root, dirs, files in os.walk(myDir, topdown=False):
        for name in files:
            if name.endswith(format):
                fullName = os.path.join(root, name)
                fileList.append(fullName)
    return fileList

# load the original image
myFileList = createFileList('gestures')

for file in myFileList:
    print(file)
    img_file = Image.open(file)
    # img_file.show()

    # get original image parameters...
    width, height = img_file.size
    format = img_file.format
    mode = img_file.mode

    # Make image Greyscale
    img_grey = img_file.convert('L')
    #img_grey.save('result.png')
    #img_grey.show()

    # Save Greyscale values
    value = np.asarray(img_grey.getdata(), dtype=np.int).reshape((img_grey.size[1], img_grey.size[0]))
    value = value.flatten()
    print(value)
    with open("train_foo.csv", 'a') as f:
        writer = csv.writer(f)
        writer.writerow(value)

gestures
gestures\1\1.jpg
[0 0 0 ... 0 0 0]
gestures\1\10.jpg
[0 0 0 ... 0 0 0]
gestures\1\100.jpg
[0 0 0 ... 0 0 0]
gestures\1\1000.jpg
[0 0 0 ... 0 0 0]
gestures\1\1001.jpg
[0 0 0 ... 0 0 0]
gestures\1\1002.jpg
[0 0 0 ... 0 0 0]
gestures\1\1003.jpg
[0 0 0 ... 0 0 0]
gestures\1\1004.jpg
[0 0 0 ... 0 0 0]
gestures\1\1005.jpg
[0 0 0 ... 0 0 0]
gestures\1\1006.jpg
[0 0 0 ... 0 0 0]
gestures\1\1007.jpg
[0 0 0 ... 0 0 0]
gestures\1\1008.jpg
[0 0 0 ... 0 0 0]
gestures\1\1009.jpg
[0 0 0 ... 0 0 0]
gestures\1\101.jpg
[0 0 0 ... 0 0 0]
gestures\1\1010.jpg
[0 0 0 ... 0 0 0]
gestures\1\1011.jpg
[0 0 0 ... 0 0 0]
gestures\1\1012.jpg
[0 0 0 ... 0 0 0]
gestures\1\1013.jpg
[0 0 0 ... 0 0 0]
gestures\1\1014.jpg
[0 0 0 ... 0 0 0]
gestures\1\1015.jpg
[0 0 0 ... 0 0 0]
gestures\1\1016.jpg
[0 0 0 ... 0 0 0]
gestures\1\1017.jpg
[0 0 0 ... 0 0 0]
gestures\1\1018.jpg
[0 0 0 ... 0 0 0]
gestures\1\1019.jpg
[0 0 0 ... 0 0 0]
gestures\1\102.jpg
[0 0 0 ... 0 0 0]
gestures\1\1020.jpg
[0 0 0 ... 0 0 0]
gestures\1\

gestures\1\13.jpg
[0 0 0 ... 0 0 0]
gestures\1\130.jpg
[0 0 0 ... 0 0 0]
gestures\1\131.jpg
[0 0 0 ... 0 0 0]
gestures\1\132.jpg
[0 0 0 ... 0 0 0]
gestures\1\133.jpg
[0 0 0 ... 0 0 0]
gestures\1\134.jpg
[0 0 0 ... 0 0 0]
gestures\1\135.jpg
[0 0 0 ... 0 0 0]
gestures\1\136.jpg
[0 0 0 ... 0 0 0]
gestures\1\137.jpg
[0 0 0 ... 0 0 0]
gestures\1\138.jpg
[0 0 0 ... 0 0 0]
gestures\1\139.jpg
[0 0 0 ... 0 0 0]
gestures\1\14.jpg
[0 0 0 ... 0 0 0]
gestures\1\140.jpg
[0 0 0 ... 0 0 0]
gestures\1\141.jpg
[0 0 0 ... 0 0 0]
gestures\1\142.jpg
[0 0 0 ... 0 0 0]
gestures\1\143.jpg
[0 0 0 ... 0 0 0]
gestures\1\144.jpg
[0 0 0 ... 0 0 0]
gestures\1\145.jpg
[0 0 0 ... 0 0 0]
gestures\1\146.jpg
[0 0 0 ... 0 0 0]
gestures\1\147.jpg
[0 0 0 ... 0 0 0]
gestures\1\148.jpg
[0 0 0 ... 0 0 0]
gestures\1\149.jpg
[0 0 0 ... 0 0 0]
gestures\1\15.jpg
[0 0 0 ... 0 0 0]
gestures\1\150.jpg
[0 0 0 ... 1 0 0]
gestures\1\151.jpg
[0 0 0 ... 0 0 0]
gestures\1\152.jpg
[0 0 0 ... 0 0 0]
gestures\1\153.jpg
[0 0 0 ... 0 0 0]
gest

gestures\1\337.jpg
[0 0 0 ... 0 0 0]
gestures\1\338.jpg
[0 0 0 ... 0 0 0]
gestures\1\339.jpg
[0 0 0 ... 0 0 0]
gestures\1\34.jpg
[0 0 0 ... 0 0 0]
gestures\1\340.jpg
[0 2 0 ... 0 0 0]
gestures\1\341.jpg
[1 0 1 ... 2 0 0]
gestures\1\342.jpg
[0 3 0 ... 0 0 0]
gestures\1\343.jpg
[0 3 0 ... 0 0 0]
gestures\1\344.jpg
[0 2 0 ... 0 0 0]
gestures\1\345.jpg
[1 0 0 ... 0 0 0]
gestures\1\346.jpg
[0 0 1 ... 0 0 0]
gestures\1\347.jpg
[1 0 0 ... 0 0 0]
gestures\1\348.jpg
[1 0 0 ... 0 0 0]
gestures\1\349.jpg
[1 0 1 ... 0 0 0]
gestures\1\35.jpg
[0 0 0 ... 0 0 0]
gestures\1\350.jpg
[1 0 0 ... 0 0 0]
gestures\1\351.jpg
[1 0 0 ... 0 0 0]
gestures\1\352.jpg
[1 2 0 ... 0 0 0]
gestures\1\353.jpg
[2 0 0 ... 0 0 0]
gestures\1\354.jpg
[0 3 0 ... 0 0 0]
gestures\1\355.jpg
[1 0 0 ... 0 0 0]
gestures\1\356.jpg
[1 1 0 ... 0 0 0]
gestures\1\357.jpg
[0 1 0 ... 0 0 0]
gestures\1\358.jpg
[0 2 0 ... 0 0 0]
gestures\1\359.jpg
[1 0 0 ... 0 0 0]
gestures\1\36.jpg
[0 0 0 ... 0 0 0]
gestures\1\360.jpg
[0 0 0 ... 0 0 0]
gest

gestures\1\546.jpg
[0 0 0 ... 0 0 0]
gestures\1\547.jpg
[0 0 0 ... 0 0 0]
gestures\1\548.jpg
[0 0 0 ... 0 0 0]
gestures\1\549.jpg
[0 0 0 ... 0 0 0]
gestures\1\55.jpg
[0 0 0 ... 0 0 0]
gestures\1\550.jpg
[0 0 0 ... 0 0 0]
gestures\1\551.jpg
[0 0 0 ... 0 0 0]
gestures\1\552.jpg
[0 0 0 ... 0 0 0]
gestures\1\553.jpg
[0 0 0 ... 0 0 0]
gestures\1\554.jpg
[0 0 0 ... 0 0 0]
gestures\1\555.jpg
[0 0 0 ... 0 0 0]
gestures\1\556.jpg
[0 0 0 ... 0 0 0]
gestures\1\557.jpg
[0 0 0 ... 0 0 0]
gestures\1\558.jpg
[0 0 0 ... 0 0 0]
gestures\1\559.jpg
[0 0 0 ... 0 0 0]
gestures\1\56.jpg
[0 0 0 ... 0 0 0]
gestures\1\560.jpg
[0 0 0 ... 0 0 0]
gestures\1\561.jpg
[0 0 0 ... 0 0 0]
gestures\1\562.jpg
[0 0 0 ... 0 0 0]
gestures\1\563.jpg
[0 0 0 ... 0 0 0]
gestures\1\564.jpg
[0 0 0 ... 0 0 0]
gestures\1\565.jpg
[0 0 0 ... 0 0 0]
gestures\1\566.jpg
[0 0 0 ... 0 0 0]
gestures\1\567.jpg
[0 0 0 ... 0 0 0]
gestures\1\568.jpg
[0 0 0 ... 0 0 0]
gestures\1\569.jpg
[0 0 0 ... 0 0 0]
gestures\1\57.jpg
[0 0 0 ... 0 0 0]
gest

gestures\1\747.jpg
[0 0 0 ... 0 0 0]
gestures\1\748.jpg
[0 0 0 ... 0 0 0]
gestures\1\749.jpg
[0 0 0 ... 0 0 0]
gestures\1\75.jpg
[0 0 0 ... 0 0 0]
gestures\1\750.jpg
[0 0 0 ... 0 0 0]
gestures\1\751.jpg
[0 0 0 ... 0 0 0]
gestures\1\752.jpg
[0 0 0 ... 0 0 0]
gestures\1\753.jpg
[0 0 0 ... 0 0 0]
gestures\1\754.jpg
[0 0 0 ... 0 0 0]
gestures\1\755.jpg
[0 0 0 ... 0 0 0]
gestures\1\756.jpg
[0 0 0 ... 0 0 0]
gestures\1\757.jpg
[0 0 0 ... 0 0 0]
gestures\1\758.jpg
[0 0 0 ... 0 0 0]
gestures\1\759.jpg
[0 0 0 ... 0 0 0]
gestures\1\76.jpg
[0 0 0 ... 0 0 0]
gestures\1\760.jpg
[0 0 0 ... 0 0 0]
gestures\1\761.jpg
[0 0 0 ... 0 0 0]
gestures\1\762.jpg
[0 0 0 ... 0 0 0]
gestures\1\763.jpg
[0 0 0 ... 0 0 0]
gestures\1\764.jpg
[0 0 0 ... 0 0 0]
gestures\1\765.jpg
[0 0 0 ... 0 0 0]
gestures\1\766.jpg
[0 0 0 ... 0 0 0]
gestures\1\767.jpg
[0 0 0 ... 0 0 0]
gestures\1\768.jpg
[0 0 0 ... 0 0 0]
gestures\1\769.jpg
[0 0 0 ... 0 0 0]
gestures\1\77.jpg
[0 0 0 ... 0 0 0]
gestures\1\770.jpg
[0 0 0 ... 0 0 0]
gest

[0 0 0 ... 0 0 0]
gestures\1\953.jpg
[0 0 0 ... 0 0 0]
gestures\1\954.jpg
[0 0 0 ... 0 0 0]
gestures\1\955.jpg
[0 0 0 ... 0 0 0]
gestures\1\956.jpg
[0 0 0 ... 0 0 0]
gestures\1\957.jpg
[0 0 0 ... 0 0 0]
gestures\1\958.jpg
[0 0 0 ... 0 0 0]
gestures\1\959.jpg
[0 0 0 ... 0 0 0]
gestures\1\96.jpg
[0 0 0 ... 0 0 0]
gestures\1\960.jpg
[0 0 0 ... 0 0 0]
gestures\1\961.jpg
[0 0 0 ... 0 0 0]
gestures\1\962.jpg
[0 0 0 ... 0 0 0]
gestures\1\963.jpg
[0 0 0 ... 0 0 0]
gestures\1\964.jpg
[0 0 0 ... 0 0 0]
gestures\1\965.jpg
[0 0 0 ... 0 0 0]
gestures\1\966.jpg
[0 0 0 ... 0 0 0]
gestures\1\967.jpg
[0 0 0 ... 0 0 0]
gestures\1\968.jpg
[0 0 0 ... 0 0 0]
gestures\1\969.jpg
[0 0 0 ... 0 0 0]
gestures\1\97.jpg
[0 0 0 ... 0 0 0]
gestures\1\970.jpg
[0 0 0 ... 0 0 0]
gestures\1\971.jpg
[0 0 0 ... 0 0 0]
gestures\1\972.jpg
[0 0 0 ... 0 0 0]
gestures\1\973.jpg
[0 0 0 ... 0 0 0]
gestures\1\974.jpg
[0 0 0 ... 0 0 0]
gestures\1\975.jpg
[0 0 0 ... 0 0 0]
gestures\1\976.jpg
[0 0 0 ... 0 0 0]
gestures\1\977.jpg
[0 

gestures\10\1149.jpg
[0 0 0 ... 0 0 0]
gestures\10\115.jpg
[0 0 0 ... 0 0 0]
gestures\10\1150.jpg
[0 0 0 ... 0 0 0]
gestures\10\1151.jpg
[0 0 0 ... 0 0 0]
gestures\10\1152.jpg
[0 0 0 ... 0 0 0]
gestures\10\1153.jpg
[0 0 0 ... 0 0 0]
gestures\10\1154.jpg
[0 0 0 ... 0 0 0]
gestures\10\1155.jpg
[0 0 0 ... 0 0 0]
gestures\10\1156.jpg
[0 0 0 ... 0 0 0]
gestures\10\1157.jpg
[0 0 0 ... 0 0 0]
gestures\10\1158.jpg
[0 0 0 ... 0 0 0]
gestures\10\1159.jpg
[0 0 0 ... 0 0 0]
gestures\10\116.jpg
[0 0 0 ... 0 0 0]
gestures\10\1160.jpg
[0 0 0 ... 0 0 0]
gestures\10\1161.jpg
[0 0 0 ... 0 0 0]
gestures\10\1162.jpg
[0 0 0 ... 0 0 0]
gestures\10\1163.jpg
[0 0 0 ... 0 0 0]
gestures\10\1164.jpg
[0 0 0 ... 0 0 0]
gestures\10\1165.jpg
[0 0 0 ... 0 0 0]
gestures\10\1166.jpg
[0 0 0 ... 0 0 0]
gestures\10\1167.jpg
[0 0 0 ... 0 0 0]
gestures\10\1168.jpg
[0 0 0 ... 0 0 0]
gestures\10\1169.jpg
[0 0 0 ... 0 0 0]
gestures\10\117.jpg
[0 0 0 ... 0 0 0]
gestures\10\1170.jpg
[0 0 0 ... 0 0 0]
gestures\10\1171.jpg
[0 0 0 

gestures\10\275.jpg
[0 0 0 ... 0 0 0]
gestures\10\276.jpg
[0 0 0 ... 0 0 0]
gestures\10\277.jpg
[0 0 0 ... 0 0 0]
gestures\10\278.jpg
[0 0 0 ... 0 0 0]
gestures\10\279.jpg
[0 0 0 ... 0 0 0]
gestures\10\28.jpg
[0 0 0 ... 0 0 0]
gestures\10\280.jpg
[0 0 0 ... 0 0 0]
gestures\10\281.jpg
[0 0 0 ... 0 0 0]
gestures\10\282.jpg
[0 0 0 ... 0 0 0]
gestures\10\283.jpg
[0 0 0 ... 0 0 0]
gestures\10\284.jpg
[0 0 0 ... 0 0 0]
gestures\10\285.jpg
[0 0 0 ... 0 0 0]
gestures\10\286.jpg
[0 0 0 ... 0 0 0]
gestures\10\287.jpg
[0 0 0 ... 0 0 0]
gestures\10\288.jpg
[0 0 0 ... 0 0 0]
gestures\10\289.jpg
[0 0 0 ... 0 0 0]
gestures\10\29.jpg
[0 0 0 ... 0 0 0]
gestures\10\290.jpg
[0 0 0 ... 0 0 0]
gestures\10\291.jpg
[0 0 0 ... 0 0 0]
gestures\10\292.jpg
[0 0 0 ... 0 0 0]
gestures\10\293.jpg
[0 0 0 ... 0 0 0]
gestures\10\294.jpg
[0 0 0 ... 0 0 0]
gestures\10\295.jpg
[0 0 0 ... 0 0 0]
gestures\10\296.jpg
[0 0 0 ... 0 0 0]
gestures\10\297.jpg
[0 0 0 ... 0 0 0]
gestures\10\298.jpg
[0 0 0 ... 0 0 0]
gestures\10\29

gestures\10\479.jpg
[0 0 0 ... 0 0 0]
gestures\10\48.jpg
[0 0 0 ... 0 0 0]
gestures\10\480.jpg
[0 0 0 ... 0 0 0]
gestures\10\481.jpg
[0 0 0 ... 0 0 0]
gestures\10\482.jpg
[0 0 0 ... 0 0 0]
gestures\10\483.jpg
[0 0 0 ... 0 0 0]
gestures\10\484.jpg
[0 0 0 ... 0 0 0]
gestures\10\485.jpg
[0 0 0 ... 0 0 0]
gestures\10\486.jpg
[0 0 0 ... 0 0 0]
gestures\10\487.jpg
[0 0 0 ... 0 0 0]
gestures\10\488.jpg
[0 0 0 ... 0 0 0]
gestures\10\489.jpg
[0 0 0 ... 0 0 0]
gestures\10\49.jpg
[0 0 0 ... 0 0 0]
gestures\10\490.jpg
[0 0 0 ... 0 0 0]
gestures\10\491.jpg
[0 0 0 ... 0 0 0]
gestures\10\492.jpg
[0 0 0 ... 0 0 0]
gestures\10\493.jpg
[0 0 0 ... 0 0 0]
gestures\10\494.jpg
[0 0 0 ... 0 0 0]
gestures\10\495.jpg
[0 0 0 ... 0 0 0]
gestures\10\496.jpg
[0 0 0 ... 0 0 0]
gestures\10\497.jpg
[0 0 0 ... 0 0 0]
gestures\10\498.jpg
[0 0 0 ... 0 0 0]
gestures\10\499.jpg
[0 0 0 ... 0 0 0]
gestures\10\5.jpg
[0 0 0 ... 0 0 0]
gestures\10\50.jpg
[0 0 0 ... 0 0 0]
gestures\10\500.jpg
[0 0 0 ... 0 0 0]
gestures\10\501.j

[0 0 0 ... 0 0 0]
gestures\10\676.jpg
[0 0 0 ... 0 0 0]
gestures\10\677.jpg
[0 0 0 ... 0 0 0]
gestures\10\678.jpg
[0 0 0 ... 0 0 0]
gestures\10\679.jpg
[0 0 0 ... 0 0 0]
gestures\10\68.jpg
[0 0 0 ... 0 0 0]
gestures\10\680.jpg
[0 0 0 ... 0 0 0]
gestures\10\681.jpg
[0 0 0 ... 0 0 0]
gestures\10\682.jpg
[0 0 0 ... 0 0 0]
gestures\10\683.jpg
[0 0 0 ... 0 0 0]
gestures\10\684.jpg
[0 0 0 ... 0 0 0]
gestures\10\685.jpg
[0 0 0 ... 0 0 0]
gestures\10\686.jpg
[0 0 0 ... 0 0 0]
gestures\10\687.jpg
[0 0 0 ... 0 0 0]
gestures\10\688.jpg
[0 0 0 ... 0 0 0]
gestures\10\689.jpg
[0 0 0 ... 0 0 0]
gestures\10\69.jpg
[0 0 0 ... 0 0 0]
gestures\10\690.jpg
[0 0 0 ... 0 0 0]
gestures\10\691.jpg
[0 0 0 ... 0 0 0]
gestures\10\692.jpg
[0 0 0 ... 0 0 0]
gestures\10\693.jpg
[0 0 0 ... 0 0 0]
gestures\10\694.jpg
[0 0 0 ... 0 0 0]
gestures\10\695.jpg
[0 0 0 ... 0 0 0]
gestures\10\696.jpg
[0 0 0 ... 0 0 0]
gestures\10\697.jpg
[0 0 0 ... 0 0 0]
gestures\10\698.jpg
[0 0 0 ... 0 0 0]
gestures\10\699.jpg
[0 0 0 ... 0 0

gestures\10\879.jpg
[0 0 0 ... 0 0 0]
gestures\10\88.jpg
[0 0 0 ... 0 0 0]
gestures\10\880.jpg
[0 0 0 ... 0 0 0]
gestures\10\881.jpg
[0 0 0 ... 0 0 0]
gestures\10\882.jpg
[0 0 0 ... 0 0 0]
gestures\10\883.jpg
[0 0 0 ... 0 0 0]
gestures\10\884.jpg
[0 0 0 ... 0 0 0]
gestures\10\885.jpg
[0 0 0 ... 0 0 0]
gestures\10\886.jpg
[0 0 0 ... 0 0 0]
gestures\10\887.jpg
[0 0 0 ... 0 0 0]
gestures\10\888.jpg
[0 0 0 ... 0 0 0]
gestures\10\889.jpg
[0 0 0 ... 0 0 0]
gestures\10\89.jpg
[0 0 0 ... 0 0 0]
gestures\10\890.jpg
[0 0 0 ... 0 0 0]
gestures\10\891.jpg
[0 0 0 ... 0 0 0]
gestures\10\892.jpg
[0 0 0 ... 0 0 0]
gestures\10\893.jpg
[0 0 0 ... 0 0 0]
gestures\10\894.jpg
[0 0 0 ... 0 0 0]
gestures\10\895.jpg
[0 0 0 ... 0 0 0]
gestures\10\896.jpg
[0 0 0 ... 0 0 0]
gestures\10\897.jpg
[0 0 0 ... 0 0 0]
gestures\10\898.jpg
[0 0 0 ... 0 0 0]
gestures\10\899.jpg
[0 0 0 ... 0 0 0]
gestures\10\9.jpg
[0 0 0 ... 0 0 0]
gestures\10\90.jpg
[0 0 0 ... 0 0 0]
gestures\10\900.jpg
[0 0 0 ... 0 0 0]
gestures\10\901.j

gestures\11\1082.jpg
[0 0 0 ... 0 0 0]
gestures\11\1083.jpg
[0 0 0 ... 0 0 0]
gestures\11\1084.jpg
[0 0 0 ... 0 0 0]
gestures\11\1085.jpg
[0 0 0 ... 0 0 0]
gestures\11\1086.jpg
[0 0 0 ... 0 0 0]
gestures\11\1087.jpg
[0 0 0 ... 0 0 0]
gestures\11\1088.jpg
[0 0 0 ... 0 0 0]
gestures\11\1089.jpg
[0 0 0 ... 0 0 0]
gestures\11\109.jpg
[0 0 0 ... 0 0 0]
gestures\11\1090.jpg
[0 0 0 ... 0 0 0]
gestures\11\1091.jpg
[0 0 0 ... 0 0 0]
gestures\11\1092.jpg
[0 0 0 ... 0 0 0]
gestures\11\1093.jpg
[0 0 0 ... 0 0 0]
gestures\11\1094.jpg
[0 0 0 ... 0 0 0]
gestures\11\1095.jpg
[0 0 0 ... 0 0 0]
gestures\11\1096.jpg
[0 0 0 ... 0 0 0]
gestures\11\1097.jpg
[0 0 0 ... 0 0 0]
gestures\11\1098.jpg
[0 0 0 ... 0 0 0]
gestures\11\1099.jpg
[0 0 0 ... 0 0 0]
gestures\11\11.jpg
[0 0 0 ... 0 0 0]
gestures\11\110.jpg
[0 0 0 ... 0 0 0]
gestures\11\1100.jpg
[0 0 0 ... 0 0 0]
gestures\11\1101.jpg
[0 0 0 ... 0 0 0]
gestures\11\1102.jpg
[0 0 0 ... 0 0 0]
gestures\11\1103.jpg
[0 0 0 ... 0 0 0]
gestures\11\1104.jpg
[0 0 0 .

[0 0 0 ... 0 0 0]
gestures\11\196.jpg
[0 0 0 ... 0 0 0]
gestures\11\197.jpg
[0 0 0 ... 0 0 0]
gestures\11\198.jpg
[0 0 0 ... 0 0 0]
gestures\11\199.jpg
[0 0 0 ... 0 0 0]
gestures\11\2.jpg
[0 0 0 ... 0 0 0]
gestures\11\20.jpg
[0 0 0 ... 0 0 0]
gestures\11\200.jpg
[0 0 0 ... 0 0 0]
gestures\11\201.jpg
[0 0 0 ... 0 0 0]
gestures\11\202.jpg
[0 0 0 ... 0 0 0]
gestures\11\203.jpg
[0 0 0 ... 0 0 0]
gestures\11\204.jpg
[0 0 0 ... 0 0 0]
gestures\11\205.jpg
[0 0 0 ... 0 0 0]
gestures\11\206.jpg
[0 0 0 ... 0 0 0]
gestures\11\207.jpg
[0 0 0 ... 0 0 0]
gestures\11\208.jpg
[0 0 0 ... 0 0 0]
gestures\11\209.jpg
[0 0 0 ... 0 0 0]
gestures\11\21.jpg
[0 0 0 ... 0 0 0]
gestures\11\210.jpg
[0 0 0 ... 0 0 0]
gestures\11\211.jpg
[0 0 0 ... 0 0 0]
gestures\11\212.jpg
[0 0 0 ... 0 0 0]
gestures\11\213.jpg
[0 0 0 ... 2 0 0]
gestures\11\214.jpg
[0 0 0 ... 0 0 0]
gestures\11\215.jpg
[0 0 0 ... 0 0 0]
gestures\11\216.jpg
[0 0 0 ... 0 0 0]
gestures\11\217.jpg
[0 0 0 ... 0 0 0]
gestures\11\218.jpg
[0 0 0 ... 2 0 0

[0 0 0 ... 0 0 0]
gestures\11\395.jpg
[0 0 0 ... 0 0 0]
gestures\11\396.jpg
[0 0 0 ... 0 0 0]
gestures\11\397.jpg
[0 0 0 ... 0 0 0]
gestures\11\398.jpg
[0 0 0 ... 0 0 0]
gestures\11\399.jpg
[0 0 0 ... 0 0 0]
gestures\11\4.jpg
[0 0 0 ... 0 0 0]
gestures\11\40.jpg
[0 0 0 ... 0 0 0]
gestures\11\400.jpg
[0 0 0 ... 0 0 0]
gestures\11\401.jpg
[0 0 0 ... 0 0 0]
gestures\11\402.jpg
[0 0 0 ... 0 0 0]
gestures\11\403.jpg
[0 0 0 ... 4 0 0]
gestures\11\404.jpg
[0 0 0 ... 2 0 0]
gestures\11\405.jpg
[0 0 0 ... 4 0 0]
gestures\11\406.jpg
[0 0 0 ... 0 0 0]
gestures\11\407.jpg
[0 0 0 ... 3 0 0]
gestures\11\408.jpg
[0 0 0 ... 0 0 0]
gestures\11\409.jpg
[0 0 0 ... 0 0 0]
gestures\11\41.jpg
[0 0 0 ... 0 0 0]
gestures\11\410.jpg
[0 0 0 ... 0 0 0]
gestures\11\411.jpg
[0 0 0 ... 0 0 0]
gestures\11\412.jpg
[0 0 0 ... 0 0 0]
gestures\11\413.jpg
[0 0 0 ... 0 0 0]
gestures\11\414.jpg
[0 0 0 ... 1 0 0]
gestures\11\415.jpg
[0 0 0 ... 1 0 0]
gestures\11\416.jpg
[0 0 0 ... 0 0 0]
gestures\11\417.jpg
[0 0 0 ... 1 0 0

gestures\11\602.jpg
[0 0 0 ... 0 0 0]
gestures\11\603.jpg
[0 0 0 ... 0 0 0]
gestures\11\604.jpg
[0 0 0 ... 2 0 0]
gestures\11\605.jpg
[0 0 0 ... 4 0 0]
gestures\11\606.jpg
[0 0 0 ... 0 0 0]
gestures\11\607.jpg
[0 0 0 ... 2 0 0]
gestures\11\608.jpg
[0 0 0 ... 0 0 0]
gestures\11\609.jpg
[0 0 0 ... 0 0 0]
gestures\11\61.jpg
[0 0 0 ... 0 0 0]
gestures\11\610.jpg
[0 0 0 ... 4 0 0]
gestures\11\611.jpg
[0 0 0 ... 0 0 0]
gestures\11\612.jpg
[0 0 0 ... 0 0 0]
gestures\11\613.jpg
[0 0 0 ... 0 0 0]
gestures\11\614.jpg
[0 0 0 ... 0 0 0]
gestures\11\615.jpg
[0 0 0 ... 0 0 0]
gestures\11\616.jpg
[0 0 0 ... 0 0 0]
gestures\11\617.jpg
[0 0 0 ... 0 0 0]
gestures\11\618.jpg
[0 0 0 ... 0 0 0]
gestures\11\619.jpg
[0 0 0 ... 0 0 0]
gestures\11\62.jpg
[0 0 0 ... 0 0 0]
gestures\11\620.jpg
[0 0 0 ... 3 0 0]
gestures\11\621.jpg
[0 0 0 ... 0 0 0]
gestures\11\622.jpg
[0 0 0 ... 0 0 0]
gestures\11\623.jpg
[0 0 0 ... 0 0 0]
gestures\11\624.jpg
[0 0 0 ... 0 0 0]
gestures\11\625.jpg
[0 0 0 ... 0 0 0]
gestures\11\62

gestures\11\818.jpg
[0 0 0 ... 0 0 0]
gestures\11\819.jpg
[0 0 0 ... 0 0 0]
gestures\11\82.jpg
[0 0 0 ... 0 0 0]
gestures\11\820.jpg
[0 0 0 ... 0 0 0]
gestures\11\821.jpg
[0 0 0 ... 0 0 0]
gestures\11\822.jpg
[0 0 0 ... 0 0 0]
gestures\11\823.jpg
[0 0 0 ... 0 0 0]
gestures\11\824.jpg
[0 0 0 ... 0 0 0]
gestures\11\825.jpg
[0 0 0 ... 0 0 0]
gestures\11\826.jpg
[0 0 0 ... 0 0 0]
gestures\11\827.jpg
[0 0 0 ... 0 0 0]
gestures\11\828.jpg
[0 0 0 ... 0 0 0]
gestures\11\829.jpg
[0 0 0 ... 0 0 0]
gestures\11\83.jpg
[0 0 0 ... 0 0 0]
gestures\11\830.jpg
[0 0 0 ... 0 0 0]
gestures\11\831.jpg
[0 0 0 ... 0 0 0]
gestures\11\832.jpg
[0 0 0 ... 0 0 0]
gestures\11\833.jpg
[0 0 0 ... 0 0 0]
gestures\11\834.jpg
[0 0 0 ... 0 0 0]
gestures\11\835.jpg
[0 0 0 ... 0 0 0]
gestures\11\836.jpg
[0 0 0 ... 0 0 0]
gestures\11\837.jpg
[0 0 0 ... 0 0 0]
gestures\11\838.jpg
[0 0 0 ... 0 0 0]
gestures\11\839.jpg
[0 0 0 ... 0 0 0]
gestures\11\84.jpg
[0 0 0 ... 0 0 0]
gestures\11\840.jpg
[0 0 0 ... 0 0 0]
gestures\11\841

[0 0 0 ... 0 0 0]
gestures\2\1012.jpg
[0 0 0 ... 0 0 0]
gestures\2\1013.jpg
[0 0 0 ... 0 0 0]
gestures\2\1014.jpg
[0 0 0 ... 0 0 0]
gestures\2\1015.jpg
[0 0 0 ... 0 0 0]
gestures\2\1016.jpg
[0 0 0 ... 0 0 0]
gestures\2\1017.jpg
[0 0 0 ... 0 0 0]
gestures\2\1018.jpg
[0 0 0 ... 0 0 0]
gestures\2\1019.jpg
[0 0 0 ... 0 0 0]
gestures\2\102.jpg
[0 0 0 ... 0 0 0]
gestures\2\1020.jpg
[0 0 0 ... 0 0 0]
gestures\2\1021.jpg
[0 0 0 ... 0 0 0]
gestures\2\1022.jpg
[0 0 0 ... 0 0 0]
gestures\2\1023.jpg
[0 0 0 ... 0 0 0]
gestures\2\1024.jpg
[0 0 0 ... 0 0 0]
gestures\2\1025.jpg
[0 0 0 ... 0 0 0]
gestures\2\1026.jpg
[0 0 0 ... 0 0 0]
gestures\2\1027.jpg
[0 0 0 ... 0 0 0]
gestures\2\1028.jpg
[0 0 0 ... 0 0 0]
gestures\2\1029.jpg
[0 0 0 ... 0 0 0]
gestures\2\103.jpg
[0 0 0 ... 0 0 0]
gestures\2\1030.jpg
[0 0 0 ... 0 0 0]
gestures\2\1031.jpg
[0 0 0 ... 0 0 0]
gestures\2\1032.jpg
[0 0 0 ... 0 0 0]
gestures\2\1033.jpg
[0 0 0 ... 0 0 0]
gestures\2\1034.jpg
[0 0 0 ... 0 0 0]
gestures\2\1035.jpg
[0 0 0 ... 0 0

[0 0 0 ... 0 0 0]
gestures\2\137.jpg
[0 0 0 ... 0 0 0]
gestures\2\138.jpg
[0 0 0 ... 0 0 0]
gestures\2\139.jpg
[0 0 0 ... 0 0 0]
gestures\2\14.jpg
[0 0 0 ... 0 0 0]
gestures\2\140.jpg
[0 0 0 ... 0 0 0]
gestures\2\141.jpg
[0 0 0 ... 0 0 0]
gestures\2\142.jpg
[0 0 0 ... 0 0 0]
gestures\2\143.jpg
[0 0 0 ... 0 0 0]
gestures\2\144.jpg
[0 0 0 ... 0 0 0]
gestures\2\145.jpg
[0 0 0 ... 0 0 0]
gestures\2\146.jpg
[0 0 0 ... 0 0 0]
gestures\2\147.jpg
[0 0 0 ... 0 0 0]
gestures\2\148.jpg
[0 0 0 ... 0 0 0]
gestures\2\149.jpg
[0 0 0 ... 0 0 0]
gestures\2\15.jpg
[0 0 0 ... 0 0 0]
gestures\2\150.jpg
[0 0 0 ... 0 0 0]
gestures\2\151.jpg
[0 0 0 ... 0 0 0]
gestures\2\152.jpg
[0 0 0 ... 0 0 0]
gestures\2\153.jpg
[0 0 0 ... 0 0 0]
gestures\2\154.jpg
[0 0 0 ... 0 0 0]
gestures\2\155.jpg
[0 0 0 ... 0 0 0]
gestures\2\156.jpg
[0 0 0 ... 0 0 0]
gestures\2\157.jpg
[0 0 0 ... 0 0 0]
gestures\2\158.jpg
[0 0 0 ... 0 0 0]
gestures\2\159.jpg
[0 0 0 ... 0 0 0]
gestures\2\16.jpg
[0 0 0 ... 0 0 0]
gestures\2\160.jpg
[0 0

gestures\2\361.jpg
[0 0 0 ... 0 0 0]
gestures\2\362.jpg
[0 0 0 ... 0 0 0]
gestures\2\363.jpg
[0 0 0 ... 0 0 0]
gestures\2\364.jpg
[0 0 0 ... 0 0 0]
gestures\2\365.jpg
[0 0 0 ... 0 0 0]
gestures\2\366.jpg
[0 0 0 ... 0 0 0]
gestures\2\367.jpg
[0 0 0 ... 0 0 0]
gestures\2\368.jpg
[0 0 0 ... 0 0 0]
gestures\2\369.jpg
[0 0 0 ... 0 0 0]
gestures\2\37.jpg
[0 0 0 ... 0 0 0]
gestures\2\370.jpg
[0 0 0 ... 0 0 0]
gestures\2\371.jpg
[0 0 0 ... 0 0 0]
gestures\2\372.jpg
[0 0 0 ... 0 0 0]
gestures\2\373.jpg
[0 0 0 ... 0 0 0]
gestures\2\374.jpg
[0 0 0 ... 0 0 0]
gestures\2\375.jpg
[0 0 0 ... 0 0 0]
gestures\2\376.jpg
[0 0 0 ... 0 0 0]
gestures\2\377.jpg
[0 0 0 ... 0 0 0]
gestures\2\378.jpg
[0 0 0 ... 0 0 0]
gestures\2\379.jpg
[0 0 0 ... 0 0 0]
gestures\2\38.jpg
[0 0 0 ... 0 0 0]
gestures\2\380.jpg
[0 0 0 ... 0 0 0]
gestures\2\381.jpg
[0 0 0 ... 0 0 0]
gestures\2\382.jpg
[0 0 0 ... 0 0 0]
gestures\2\383.jpg
[0 0 0 ... 0 0 0]
gestures\2\384.jpg
[0 0 0 ... 0 0 0]
gestures\2\385.jpg
[0 0 0 ... 0 0 0]
ges

[0 0 0 ... 0 0 0]
gestures\2\576.jpg
[0 0 0 ... 0 0 0]
gestures\2\577.jpg
[0 0 0 ... 0 0 0]
gestures\2\578.jpg
[0 0 0 ... 0 0 0]
gestures\2\579.jpg
[0 0 0 ... 0 0 0]
gestures\2\58.jpg
[0 0 0 ... 0 0 0]
gestures\2\580.jpg
[0 0 0 ... 0 0 0]
gestures\2\581.jpg
[0 0 0 ... 0 0 0]
gestures\2\582.jpg
[0 0 0 ... 0 0 0]
gestures\2\583.jpg
[0 0 0 ... 0 0 0]
gestures\2\584.jpg
[0 0 0 ... 0 0 0]
gestures\2\585.jpg
[0 0 0 ... 0 0 0]
gestures\2\586.jpg
[0 0 0 ... 0 0 0]
gestures\2\587.jpg
[0 0 0 ... 0 0 0]
gestures\2\588.jpg
[0 0 0 ... 0 0 0]
gestures\2\589.jpg
[0 0 0 ... 0 0 0]
gestures\2\59.jpg
[0 0 0 ... 0 0 0]
gestures\2\590.jpg
[0 0 0 ... 0 0 0]
gestures\2\591.jpg
[0 0 0 ... 0 0 0]
gestures\2\592.jpg
[0 0 0 ... 0 0 0]
gestures\2\593.jpg
[0 0 0 ... 0 0 0]
gestures\2\594.jpg
[0 0 0 ... 0 0 0]
gestures\2\595.jpg
[0 0 0 ... 0 0 0]
gestures\2\596.jpg
[0 0 0 ... 0 0 0]
gestures\2\597.jpg
[0 0 0 ... 0 0 0]
gestures\2\598.jpg
[0 0 0 ... 0 0 0]
gestures\2\599.jpg
[0 0 0 ... 0 0 0]
gestures\2\6.jpg
[0 0 

gestures\2\786.jpg
[0 0 0 ... 0 0 0]
gestures\2\787.jpg
[0 0 0 ... 0 0 0]
gestures\2\788.jpg
[0 0 0 ... 0 0 0]
gestures\2\789.jpg
[0 0 0 ... 0 0 0]
gestures\2\79.jpg
[0 0 0 ... 0 0 0]
gestures\2\790.jpg
[0 0 0 ... 0 0 0]
gestures\2\791.jpg
[0 0 0 ... 0 0 0]
gestures\2\792.jpg
[0 0 0 ... 0 0 0]
gestures\2\793.jpg
[0 0 0 ... 0 0 0]
gestures\2\794.jpg
[0 0 0 ... 0 0 0]
gestures\2\795.jpg
[0 0 0 ... 0 0 0]
gestures\2\796.jpg
[0 0 0 ... 0 0 0]
gestures\2\797.jpg
[0 0 0 ... 0 0 0]
gestures\2\798.jpg
[0 0 0 ... 0 0 0]
gestures\2\799.jpg
[0 0 0 ... 0 0 0]
gestures\2\8.jpg
[0 0 0 ... 0 0 0]
gestures\2\80.jpg
[0 0 0 ... 0 0 0]
gestures\2\800.jpg
[0 0 0 ... 0 0 0]
gestures\2\801.jpg
[0 0 0 ... 0 0 0]
gestures\2\802.jpg
[0 0 0 ... 0 0 0]
gestures\2\803.jpg
[0 0 0 ... 0 0 0]
gestures\2\804.jpg
[0 0 0 ... 0 0 0]
gestures\2\805.jpg
[0 0 0 ... 0 0 0]
gestures\2\806.jpg
[0 0 0 ... 0 0 0]
gestures\2\807.jpg
[0 0 0 ... 0 0 0]
gestures\2\808.jpg
[0 0 0 ... 0 0 0]
gestures\2\809.jpg
[0 0 0 ... 0 0 0]
gestu

[0 0 0 ... 0 0 0]
gestures\2\998.jpg
[0 0 0 ... 0 0 0]
gestures\2\999.jpg
[0 0 0 ... 0 0 0]
gestures\3\1.jpg
[0 0 0 ... 0 0 0]
gestures\3\10.jpg
[0 0 0 ... 1 0 0]
gestures\3\100.jpg
[0 0 0 ... 2 0 0]
gestures\3\1000.jpg
[0 0 0 ... 3 0 0]
gestures\3\1001.jpg
[0 0 0 ... 2 0 0]
gestures\3\1002.jpg
[0 0 0 ... 2 0 0]
gestures\3\1003.jpg
[0 0 0 ... 2 0 0]
gestures\3\1004.jpg
[0 0 0 ... 0 0 0]
gestures\3\1005.jpg
[0 0 0 ... 2 0 0]
gestures\3\1006.jpg
[0 0 0 ... 2 0 0]
gestures\3\1007.jpg
[0 0 0 ... 0 0 0]
gestures\3\1008.jpg
[0 0 0 ... 2 0 0]
gestures\3\1009.jpg
[0 0 0 ... 0 0 0]
gestures\3\101.jpg
[0 0 0 ... 0 0 0]
gestures\3\1010.jpg
[0 0 0 ... 0 0 0]
gestures\3\1011.jpg
[0 0 0 ... 0 0 0]
gestures\3\1012.jpg
[0 0 0 ... 0 0 0]
gestures\3\1013.jpg
[0 0 0 ... 2 0 0]
gestures\3\1014.jpg
[0 0 0 ... 3 0 0]
gestures\3\1015.jpg
[0 0 0 ... 0 0 0]
gestures\3\1016.jpg
[0 0 0 ... 0 0 0]
gestures\3\1017.jpg
[0 0 0 ... 0 0 0]
gestures\3\1018.jpg
[0 0 0 ... 2 0 0]
gestures\3\1019.jpg
[0 0 0 ... 0 0 0]
ges

[0 0 0 ... 2 0 0]
gestures\3\121.jpg
[0 0 0 ... 1 0 0]
gestures\3\122.jpg
[0 0 0 ... 0 0 0]
gestures\3\123.jpg
[0 0 0 ... 0 0 0]
gestures\3\124.jpg
[0 0 0 ... 0 0 0]
gestures\3\125.jpg
[0 0 0 ... 0 0 0]
gestures\3\126.jpg
[0 0 0 ... 1 0 0]
gestures\3\127.jpg
[0 0 0 ... 1 0 0]
gestures\3\128.jpg
[0 0 0 ... 1 0 0]
gestures\3\129.jpg
[0 0 0 ... 1 0 0]
gestures\3\13.jpg
[0 0 0 ... 1 0 0]
gestures\3\130.jpg
[0 0 0 ... 0 0 0]
gestures\3\131.jpg
[0 0 0 ... 0 0 0]
gestures\3\132.jpg
[0 0 0 ... 0 0 0]
gestures\3\133.jpg
[0 0 0 ... 2 0 0]
gestures\3\134.jpg
[0 0 0 ... 0 0 0]
gestures\3\135.jpg
[0 0 0 ... 0 0 0]
gestures\3\136.jpg
[0 0 0 ... 0 0 0]
gestures\3\137.jpg
[0 0 0 ... 0 0 0]
gestures\3\138.jpg
[0 0 0 ... 1 0 0]
gestures\3\139.jpg
[0 0 0 ... 1 0 0]
gestures\3\14.jpg
[0 0 0 ... 0 0 0]
gestures\3\140.jpg
[0 0 0 ... 1 0 0]
gestures\3\141.jpg
[0 0 0 ... 0 0 0]
gestures\3\142.jpg
[0 0 0 ... 0 0 0]
gestures\3\143.jpg
[0 0 0 ... 0 0 0]
gestures\3\144.jpg
[0 0 0 ... 0 0 0]
gestures\3\145.jpg
[0 

[0 0 0 ... 0 0 0]
gestures\3\324.jpg
[0 0 0 ... 0 0 0]
gestures\3\325.jpg
[0 0 0 ... 0 0 0]
gestures\3\326.jpg
[0 0 0 ... 0 0 0]
gestures\3\327.jpg
[0 0 0 ... 0 0 0]
gestures\3\328.jpg
[0 0 0 ... 0 0 0]
gestures\3\329.jpg
[0 0 0 ... 0 0 0]
gestures\3\33.jpg
[0 0 0 ... 0 0 0]
gestures\3\330.jpg
[0 0 0 ... 0 0 0]
gestures\3\331.jpg
[0 0 0 ... 0 0 0]
gestures\3\332.jpg
[0 0 0 ... 0 0 0]
gestures\3\333.jpg
[0 0 0 ... 0 0 0]
gestures\3\334.jpg
[0 0 0 ... 0 0 0]
gestures\3\335.jpg
[0 0 0 ... 0 0 0]
gestures\3\336.jpg
[0 0 0 ... 0 0 0]
gestures\3\337.jpg
[0 0 0 ... 0 0 0]
gestures\3\338.jpg
[0 0 0 ... 0 0 0]
gestures\3\339.jpg
[0 0 0 ... 0 0 0]
gestures\3\34.jpg
[0 0 0 ... 2 0 0]
gestures\3\340.jpg
[0 0 0 ... 0 0 0]
gestures\3\341.jpg
[0 0 0 ... 0 0 0]
gestures\3\342.jpg
[0 0 0 ... 0 0 0]
gestures\3\343.jpg
[0 0 0 ... 0 0 0]
gestures\3\344.jpg
[0 0 0 ... 1 0 0]
gestures\3\345.jpg
[0 0 0 ... 0 0 0]
gestures\3\346.jpg
[0 0 0 ... 1 0 0]
gestures\3\347.jpg
[0 0 0 ... 1 0 0]
gestures\3\348.jpg
[0 

gestures\3\526.jpg
[0 0 0 ... 0 0 0]
gestures\3\527.jpg
[0 0 0 ... 0 0 0]
gestures\3\528.jpg
[0 0 0 ... 0 0 0]
gestures\3\529.jpg
[0 0 0 ... 0 0 0]
gestures\3\53.jpg
[0 0 0 ... 0 0 0]
gestures\3\530.jpg
[0 0 0 ... 0 0 0]
gestures\3\531.jpg
[0 0 0 ... 0 0 0]
gestures\3\532.jpg
[0 0 0 ... 0 0 0]
gestures\3\533.jpg
[0 0 0 ... 0 0 0]
gestures\3\534.jpg
[0 0 0 ... 0 0 0]
gestures\3\535.jpg
[0 0 0 ... 0 0 0]
gestures\3\536.jpg
[0 0 0 ... 0 0 0]
gestures\3\537.jpg
[0 0 0 ... 0 0 0]
gestures\3\538.jpg
[0 0 0 ... 0 0 0]
gestures\3\539.jpg
[0 0 0 ... 0 0 0]
gestures\3\54.jpg
[0 0 0 ... 0 0 0]
gestures\3\540.jpg
[0 0 0 ... 0 0 0]
gestures\3\541.jpg
[0 0 0 ... 0 0 0]
gestures\3\542.jpg
[0 0 0 ... 0 0 0]
gestures\3\543.jpg
[0 0 0 ... 0 0 0]
gestures\3\544.jpg
[0 0 0 ... 0 0 0]
gestures\3\545.jpg
[0 0 0 ... 0 0 0]
gestures\3\546.jpg
[0 0 0 ... 0 0 0]
gestures\3\547.jpg
[0 0 0 ... 0 0 0]
gestures\3\548.jpg
[0 0 0 ... 0 0 0]
gestures\3\549.jpg
[0 0 0 ... 0 0 0]
gestures\3\55.jpg
[0 0 0 ... 0 0 0]
gest

gestures\3\73.jpg
[0 0 0 ... 1 0 0]
gestures\3\730.jpg
[0 0 0 ... 0 0 0]
gestures\3\731.jpg
[0 0 0 ... 0 0 0]
gestures\3\732.jpg
[0 0 0 ... 0 0 0]
gestures\3\733.jpg
[0 0 0 ... 0 0 0]
gestures\3\734.jpg
[0 0 0 ... 0 0 0]
gestures\3\735.jpg
[0 0 0 ... 0 0 0]
gestures\3\736.jpg
[0 0 0 ... 2 0 0]
gestures\3\737.jpg
[0 0 0 ... 0 0 0]
gestures\3\738.jpg
[0 0 0 ... 2 0 0]
gestures\3\739.jpg
[0 0 0 ... 0 0 0]
gestures\3\74.jpg
[0 0 0 ... 0 0 0]
gestures\3\740.jpg
[0 0 0 ... 2 0 0]
gestures\3\741.jpg
[0 0 0 ... 0 0 0]
gestures\3\742.jpg
[0 0 0 ... 0 0 0]
gestures\3\743.jpg
[0 0 0 ... 0 0 0]
gestures\3\744.jpg
[0 0 0 ... 4 0 0]
gestures\3\745.jpg
[0 0 0 ... 0 0 0]
gestures\3\746.jpg
[0 0 0 ... 2 0 0]
gestures\3\747.jpg
[0 0 0 ... 0 0 0]
gestures\3\748.jpg
[0 0 0 ... 2 0 0]
gestures\3\749.jpg
[0 0 0 ... 0 0 0]
gestures\3\75.jpg
[0 0 0 ... 0 0 0]
gestures\3\750.jpg
[0 0 0 ... 3 0 0]
gestures\3\751.jpg
[0 0 0 ... 0 0 0]
gestures\3\752.jpg
[0 0 0 ... 0 0 0]
gestures\3\753.jpg
[0 0 0 ... 0 0 0]
gest

[0 0 0 ... 0 0 0]
gestures\3\939.jpg
[0 0 0 ... 0 0 0]
gestures\3\94.jpg
[0 0 0 ... 0 0 0]
gestures\3\940.jpg
[0 0 0 ... 0 0 0]
gestures\3\941.jpg
[0 0 0 ... 0 0 0]
gestures\3\942.jpg
[0 0 0 ... 0 0 0]
gestures\3\943.jpg
[0 0 0 ... 0 0 0]
gestures\3\944.jpg
[0 0 0 ... 0 0 0]
gestures\3\945.jpg
[0 0 0 ... 0 0 0]
gestures\3\946.jpg
[0 0 0 ... 0 0 0]
gestures\3\947.jpg
[0 0 0 ... 0 0 0]
gestures\3\948.jpg
[0 0 0 ... 0 0 0]
gestures\3\949.jpg
[0 0 0 ... 0 0 0]
gestures\3\95.jpg
[0 0 0 ... 0 0 0]
gestures\3\950.jpg
[0 0 0 ... 0 0 0]
gestures\3\951.jpg
[0 0 0 ... 1 0 0]
gestures\3\952.jpg
[0 0 0 ... 0 0 0]
gestures\3\953.jpg
[0 0 0 ... 1 0 0]
gestures\3\954.jpg
[0 0 0 ... 0 0 0]
gestures\3\955.jpg
[0 0 0 ... 0 0 0]
gestures\3\956.jpg
[0 0 0 ... 0 0 0]
gestures\3\957.jpg
[0 0 0 ... 0 0 0]
gestures\3\958.jpg
[0 0 0 ... 1 0 0]
gestures\3\959.jpg
[0 0 0 ... 0 0 0]
gestures\3\96.jpg
[0 0 0 ... 2 0 0]
gestures\3\960.jpg
[0 0 0 ... 0 0 0]
gestures\3\961.jpg
[0 0 0 ... 0 0 0]
gestures\3\962.jpg
[0 0

[0 0 0 ... 0 0 0]
gestures\4\1135.jpg
[0 0 0 ... 1 0 0]
gestures\4\1136.jpg
[0 0 0 ... 0 0 0]
gestures\4\1137.jpg
[0 0 0 ... 0 0 0]
gestures\4\1138.jpg
[0 0 0 ... 0 0 0]
gestures\4\1139.jpg
[0 0 0 ... 0 0 0]
gestures\4\114.jpg
[0 0 0 ... 0 0 0]
gestures\4\1140.jpg
[0 0 0 ... 0 0 0]
gestures\4\1141.jpg
[0 0 0 ... 1 0 0]
gestures\4\1142.jpg
[0 0 0 ... 0 0 0]
gestures\4\1143.jpg
[0 0 0 ... 0 0 0]
gestures\4\1144.jpg
[0 0 0 ... 0 0 0]
gestures\4\1145.jpg
[0 0 0 ... 1 0 0]
gestures\4\1146.jpg
[0 0 0 ... 0 0 0]
gestures\4\1147.jpg
[0 0 0 ... 0 0 0]
gestures\4\1148.jpg
[0 0 0 ... 0 0 0]
gestures\4\1149.jpg
[0 0 0 ... 0 0 0]
gestures\4\115.jpg
[0 0 0 ... 0 0 0]
gestures\4\1150.jpg
[0 0 0 ... 0 0 0]
gestures\4\1151.jpg
[0 0 0 ... 0 0 0]
gestures\4\1152.jpg
[0 0 0 ... 0 0 0]
gestures\4\1153.jpg
[0 0 0 ... 0 0 0]
gestures\4\1154.jpg
[0 0 0 ... 0 0 0]
gestures\4\1155.jpg
[0 0 0 ... 0 0 0]
gestures\4\1156.jpg
[0 0 0 ... 1 0 0]
gestures\4\1157.jpg
[0 0 0 ... 0 0 0]
gestures\4\1158.jpg
[0 0 0 ... 0 0

[0 0 0 ... 0 0 0]
gestures\4\278.jpg
[0 0 0 ... 0 0 0]
gestures\4\279.jpg
[0 0 0 ... 0 0 0]
gestures\4\28.jpg
[0 0 0 ... 0 0 0]
gestures\4\280.jpg
[0 0 0 ... 0 0 0]
gestures\4\281.jpg
[0 0 0 ... 0 0 0]
gestures\4\282.jpg
[0 0 0 ... 0 0 0]
gestures\4\283.jpg
[0 0 0 ... 1 0 0]
gestures\4\284.jpg
[0 0 0 ... 0 0 0]
gestures\4\285.jpg
[0 0 0 ... 1 0 0]
gestures\4\286.jpg
[0 0 0 ... 4 0 0]
gestures\4\287.jpg
[0 0 0 ... 0 0 0]
gestures\4\288.jpg
[0 0 0 ... 1 0 0]
gestures\4\289.jpg
[0 0 0 ... 0 0 0]
gestures\4\29.jpg
[0 0 0 ... 1 0 0]
gestures\4\290.jpg
[0 0 0 ... 0 0 0]
gestures\4\291.jpg
[0 0 0 ... 0 0 0]
gestures\4\292.jpg
[0 0 0 ... 2 0 0]
gestures\4\293.jpg
[0 0 0 ... 0 0 0]
gestures\4\294.jpg
[0 0 0 ... 1 0 0]
gestures\4\295.jpg
[0 0 0 ... 2 0 0]
gestures\4\296.jpg
[0 0 0 ... 0 0 0]
gestures\4\297.jpg
[0 0 0 ... 0 0 0]
gestures\4\298.jpg
[0 0 0 ... 0 0 0]
gestures\4\299.jpg
[0 0 0 ... 0 0 0]
gestures\4\3.jpg
[0 0 0 ... 1 0 0]
gestures\4\30.jpg
[0 0 0 ... 0 0 0]
gestures\4\300.jpg
[0 0 0

gestures\4\513.jpg
[0 0 0 ... 0 0 0]
gestures\4\514.jpg
[0 0 0 ... 0 0 0]
gestures\4\515.jpg
[0 0 0 ... 0 0 0]
gestures\4\516.jpg
[0 0 0 ... 2 0 0]
gestures\4\517.jpg
[0 0 0 ... 0 0 0]
gestures\4\518.jpg
[0 0 0 ... 0 0 0]
gestures\4\519.jpg
[0 0 0 ... 0 0 0]
gestures\4\52.jpg
[0 0 0 ... 0 0 0]
gestures\4\520.jpg
[0 0 0 ... 0 0 0]
gestures\4\521.jpg
[0 0 0 ... 2 0 0]
gestures\4\522.jpg
[0 0 0 ... 0 0 0]
gestures\4\523.jpg
[0 0 0 ... 0 0 0]
gestures\4\524.jpg
[0 0 0 ... 0 0 0]
gestures\4\525.jpg
[0 0 0 ... 0 0 0]
gestures\4\526.jpg
[0 0 0 ... 0 0 0]
gestures\4\527.jpg
[0 0 0 ... 0 0 0]
gestures\4\528.jpg
[0 0 0 ... 0 0 0]
gestures\4\529.jpg
[0 0 0 ... 0 0 0]
gestures\4\53.jpg
[0 0 0 ... 0 0 0]
gestures\4\530.jpg
[0 0 0 ... 1 0 0]
gestures\4\531.jpg
[0 0 0 ... 0 0 0]
gestures\4\532.jpg
[0 0 0 ... 2 0 0]
gestures\4\533.jpg
[0 0 0 ... 0 0 0]
gestures\4\534.jpg
[0 0 0 ... 0 0 0]
gestures\4\535.jpg
[0 0 0 ... 0 0 0]
gestures\4\536.jpg
[0 0 0 ... 0 0 0]
gestures\4\537.jpg
[0 0 0 ... 0 0 0]
ges

[0 0 0 ... 0 0 0]
gestures\4\728.jpg
[0 0 0 ... 0 0 0]
gestures\4\729.jpg
[0 0 0 ... 0 0 0]
gestures\4\73.jpg
[0 0 0 ... 0 0 0]
gestures\4\730.jpg
[0 0 0 ... 0 0 0]
gestures\4\731.jpg
[0 0 0 ... 0 0 0]
gestures\4\732.jpg
[0 0 0 ... 0 0 0]
gestures\4\733.jpg
[0 0 0 ... 0 0 0]
gestures\4\734.jpg
[0 0 0 ... 0 0 0]
gestures\4\735.jpg
[0 0 0 ... 0 0 0]
gestures\4\736.jpg
[0 0 0 ... 0 0 0]
gestures\4\737.jpg
[0 0 0 ... 0 0 0]
gestures\4\738.jpg
[0 0 0 ... 0 0 0]
gestures\4\739.jpg
[0 0 0 ... 0 0 0]
gestures\4\74.jpg
[0 0 0 ... 1 0 0]
gestures\4\740.jpg
[0 0 0 ... 0 0 0]
gestures\4\741.jpg
[0 0 0 ... 0 0 0]
gestures\4\742.jpg
[0 0 0 ... 0 0 0]
gestures\4\743.jpg
[0 0 0 ... 0 0 0]
gestures\4\744.jpg
[0 0 0 ... 0 0 0]
gestures\4\745.jpg
[0 0 0 ... 0 0 0]
gestures\4\746.jpg
[0 0 0 ... 0 0 0]
gestures\4\747.jpg
[0 0 0 ... 0 0 0]
gestures\4\748.jpg
[0 0 0 ... 0 0 0]
gestures\4\749.jpg
[0 0 0 ... 0 0 0]
gestures\4\75.jpg
[0 0 0 ... 0 0 0]
gestures\4\750.jpg
[0 0 0 ... 0 0 0]
gestures\4\751.jpg
[0 0

gestures\4\940.jpg
[0 0 0 ... 1 0 0]
gestures\4\941.jpg
[0 0 0 ... 0 0 0]
gestures\4\942.jpg
[0 0 0 ... 0 0 0]
gestures\4\943.jpg
[0 0 0 ... 0 0 0]
gestures\4\944.jpg
[0 0 0 ... 0 0 0]
gestures\4\945.jpg
[0 0 0 ... 0 0 0]
gestures\4\946.jpg
[0 0 0 ... 0 0 0]
gestures\4\947.jpg
[0 0 0 ... 0 0 0]
gestures\4\948.jpg
[0 0 0 ... 0 0 0]
gestures\4\949.jpg
[0 0 0 ... 0 0 0]
gestures\4\95.jpg
[0 0 0 ... 1 0 0]
gestures\4\950.jpg
[0 0 0 ... 0 0 0]
gestures\4\951.jpg
[0 0 0 ... 2 0 0]
gestures\4\952.jpg
[0 0 0 ... 0 0 0]
gestures\4\953.jpg
[0 0 0 ... 0 0 0]
gestures\4\954.jpg
[0 0 0 ... 0 0 0]
gestures\4\955.jpg
[0 0 0 ... 0 0 0]
gestures\4\956.jpg
[0 0 0 ... 0 0 0]
gestures\4\957.jpg
[0 0 0 ... 0 0 0]
gestures\4\958.jpg
[0 0 0 ... 0 0 0]
gestures\4\959.jpg
[0 0 0 ... 1 0 0]
gestures\4\96.jpg
[0 0 0 ... 1 0 0]
gestures\4\960.jpg
[0 0 0 ... 1 0 0]
gestures\4\961.jpg
[0 0 0 ... 0 0 0]
gestures\4\962.jpg
[0 0 0 ... 1 0 0]
gestures\4\963.jpg
[0 0 0 ... 1 0 0]
gestures\4\964.jpg
[0 0 0 ... 0 0 0]
ges

gestures\5\1140.jpg
[0 0 0 ... 0 0 0]
gestures\5\1141.jpg
[0 0 0 ... 0 0 0]
gestures\5\1142.jpg
[0 0 0 ... 0 0 0]
gestures\5\1143.jpg
[0 0 0 ... 0 0 0]
gestures\5\1144.jpg
[0 0 0 ... 0 0 0]
gestures\5\1145.jpg
[0 0 0 ... 0 0 0]
gestures\5\1146.jpg
[0 0 0 ... 0 0 0]
gestures\5\1147.jpg
[0 0 0 ... 0 0 0]
gestures\5\1148.jpg
[0 0 0 ... 0 0 0]
gestures\5\1149.jpg
[0 0 0 ... 0 0 0]
gestures\5\115.jpg
[0 0 0 ... 0 0 0]
gestures\5\1150.jpg
[0 0 0 ... 0 0 0]
gestures\5\1151.jpg
[0 0 0 ... 0 0 0]
gestures\5\1152.jpg
[0 0 0 ... 0 0 0]
gestures\5\1153.jpg
[0 0 0 ... 0 0 0]
gestures\5\1154.jpg
[0 0 0 ... 0 0 0]
gestures\5\1155.jpg
[0 0 0 ... 0 0 0]
gestures\5\1156.jpg
[0 0 0 ... 0 0 0]
gestures\5\1157.jpg
[0 0 0 ... 0 0 0]
gestures\5\1158.jpg
[0 0 0 ... 0 0 0]
gestures\5\1159.jpg
[0 0 0 ... 0 0 0]
gestures\5\116.jpg
[0 0 0 ... 0 0 0]
gestures\5\1160.jpg
[0 0 0 ... 0 0 0]
gestures\5\1161.jpg
[0 0 0 ... 0 0 0]
gestures\5\1162.jpg
[0 0 0 ... 0 0 0]
gestures\5\1163.jpg
[0 0 0 ... 0 0 0]
gestures\5\116

gestures\5\277.jpg
[0 1 0 ... 0 0 0]
gestures\5\278.jpg
[0 4 0 ... 0 0 0]
gestures\5\279.jpg
[1 0 0 ... 0 0 0]
gestures\5\28.jpg
[0 0 0 ... 0 0 0]
gestures\5\280.jpg
[0 2 0 ... 0 0 0]
gestures\5\281.jpg
[0 0 1 ... 0 0 0]
gestures\5\282.jpg
[0 0 1 ... 0 0 0]
gestures\5\283.jpg
[1 0 2 ... 0 0 0]
gestures\5\284.jpg
[0 0 1 ... 0 0 0]
gestures\5\285.jpg
[0 0 0 ... 0 0 0]
gestures\5\286.jpg
[0 0 1 ... 0 0 0]
gestures\5\287.jpg
[1 0 0 ... 0 0 0]
gestures\5\288.jpg
[1 0 0 ... 0 0 0]
gestures\5\289.jpg
[0 2 0 ... 0 0 0]
gestures\5\29.jpg
[0 0 0 ... 0 0 0]
gestures\5\290.jpg
[0 0 2 ... 0 0 0]
gestures\5\291.jpg
[0 0 1 ... 0 0 0]
gestures\5\292.jpg
[0 0 0 ... 1 0 0]
gestures\5\293.jpg
[0 4 0 ... 0 0 0]
gestures\5\294.jpg
[1 0 0 ... 0 0 0]
gestures\5\295.jpg
[1 1 0 ... 0 0 0]
gestures\5\296.jpg
[0 0 0 ... 0 0 0]
gestures\5\297.jpg
[0 0 3 ... 0 0 0]
gestures\5\298.jpg
[0 0 0 ... 0 0 0]
gestures\5\299.jpg
[0 2 0 ... 0 0 0]
gestures\5\3.jpg
[0 0 0 ... 0 0 0]
gestures\5\30.jpg
[0 0 0 ... 0 0 0]
gestur

[0 0 0 ... 0 0 0]
gestures\5\508.jpg
[0 0 0 ... 0 0 0]
gestures\5\509.jpg
[0 0 0 ... 0 0 0]
gestures\5\51.jpg
[0 0 0 ... 0 0 0]
gestures\5\510.jpg
[0 0 0 ... 0 0 0]
gestures\5\511.jpg
[0 0 0 ... 0 0 0]
gestures\5\512.jpg
[0 0 0 ... 0 0 0]
gestures\5\513.jpg
[0 0 0 ... 0 0 0]
gestures\5\514.jpg
[0 0 0 ... 0 0 0]
gestures\5\515.jpg
[0 0 0 ... 0 0 0]
gestures\5\516.jpg
[0 0 0 ... 0 0 0]
gestures\5\517.jpg
[0 0 0 ... 0 0 0]
gestures\5\518.jpg
[0 0 0 ... 0 0 0]
gestures\5\519.jpg
[0 0 0 ... 0 0 0]
gestures\5\52.jpg
[0 0 0 ... 0 0 0]
gestures\5\520.jpg
[0 0 0 ... 0 0 0]
gestures\5\521.jpg
[0 0 0 ... 0 0 0]
gestures\5\522.jpg
[0 0 0 ... 0 0 0]
gestures\5\523.jpg
[0 0 0 ... 0 0 0]
gestures\5\524.jpg
[0 0 0 ... 0 0 0]
gestures\5\525.jpg
[0 0 0 ... 0 0 0]
gestures\5\526.jpg
[0 0 0 ... 0 0 0]
gestures\5\527.jpg
[0 0 0 ... 0 0 0]
gestures\5\528.jpg
[0 0 0 ... 0 0 0]
gestures\5\529.jpg
[0 0 0 ... 0 0 0]
gestures\5\53.jpg
[0 0 0 ... 0 0 0]
gestures\5\530.jpg
[0 0 0 ... 0 0 0]
gestures\5\531.jpg
[0 0

[0 0 0 ... 0 0 0]
gestures\5\732.jpg
[0 0 0 ... 0 0 0]
gestures\5\733.jpg
[0 0 4 ... 0 0 0]
gestures\5\734.jpg
[0 0 0 ... 0 0 0]
gestures\5\735.jpg
[0 0 1 ... 0 0 0]
gestures\5\736.jpg
[0 0 0 ... 0 0 0]
gestures\5\737.jpg
[0 0 0 ... 0 0 0]
gestures\5\738.jpg
[0 0 0 ... 0 0 0]
gestures\5\739.jpg
[0 0 0 ... 0 0 0]
gestures\5\74.jpg
[0 0 0 ... 0 0 0]
gestures\5\740.jpg
[0 0 0 ... 0 0 0]
gestures\5\741.jpg
[0 0 0 ... 0 0 0]
gestures\5\742.jpg
[0 0 0 ... 0 0 0]
gestures\5\743.jpg
[0 0 0 ... 0 0 0]
gestures\5\744.jpg
[0 0 0 ... 0 0 0]
gestures\5\745.jpg
[0 0 0 ... 0 0 0]
gestures\5\746.jpg
[0 0 0 ... 0 0 0]
gestures\5\747.jpg
[0 0 0 ... 0 0 0]
gestures\5\748.jpg
[0 0 0 ... 0 0 0]
gestures\5\749.jpg
[0 0 0 ... 0 0 0]
gestures\5\75.jpg
[0 0 0 ... 0 0 0]
gestures\5\750.jpg
[0 0 0 ... 0 0 0]
gestures\5\751.jpg
[0 0 0 ... 0 0 0]
gestures\5\752.jpg
[0 0 0 ... 0 0 0]
gestures\5\753.jpg
[0 0 0 ... 0 0 0]
gestures\5\754.jpg
[0 0 0 ... 0 0 0]
gestures\5\755.jpg
[0 0 0 ... 0 0 0]
gestures\5\756.jpg
[0 

[0 0 0 ... 0 0 0]
gestures\5\942.jpg
[0 0 0 ... 0 0 0]
gestures\5\943.jpg
[0 0 0 ... 0 0 0]
gestures\5\944.jpg
[0 0 0 ... 0 0 0]
gestures\5\945.jpg
[0 0 0 ... 0 0 0]
gestures\5\946.jpg
[0 0 0 ... 0 0 0]
gestures\5\947.jpg
[0 0 0 ... 0 0 0]
gestures\5\948.jpg
[3 0 1 ... 0 0 0]
gestures\5\949.jpg
[0 1 0 ... 0 0 0]
gestures\5\95.jpg
[0 0 0 ... 0 0 0]
gestures\5\950.jpg
[1 0 0 ... 0 0 0]
gestures\5\951.jpg
[0 3 0 ... 0 0 0]
gestures\5\952.jpg
[0 3 0 ... 0 0 0]
gestures\5\953.jpg
[0 0 1 ... 0 0 0]
gestures\5\954.jpg
[2 1 0 ... 0 0 0]
gestures\5\955.jpg
[0 1 0 ... 0 0 0]
gestures\5\956.jpg
[1 0 0 ... 0 0 0]
gestures\5\957.jpg
[0 1 0 ... 0 0 0]
gestures\5\958.jpg
[1 0 1 ... 0 0 0]
gestures\5\959.jpg
[0 1 0 ... 0 0 0]
gestures\5\96.jpg
[0 0 0 ... 0 0 0]
gestures\5\960.jpg
[1 0 0 ... 0 0 0]
gestures\5\961.jpg
[0 0 0 ... 0 0 0]
gestures\5\962.jpg
[0 0 0 ... 0 0 0]
gestures\5\963.jpg
[0 0 0 ... 0 0 0]
gestures\5\964.jpg
[0 0 0 ... 0 0 0]
gestures\5\965.jpg
[0 0 0 ... 0 0 0]
gestures\5\966.jpg
[0 

[0 0 0 ... 0 0 0]
gestures\6\1145.jpg
[0 0 0 ... 0 0 0]
gestures\6\1146.jpg
[0 0 0 ... 0 0 0]
gestures\6\1147.jpg
[0 0 0 ... 0 0 0]
gestures\6\1148.jpg
[0 0 0 ... 0 0 0]
gestures\6\1149.jpg
[0 0 0 ... 0 0 0]
gestures\6\115.jpg
[0 0 0 ... 0 0 0]
gestures\6\1150.jpg
[0 0 0 ... 0 0 0]
gestures\6\1151.jpg
[0 0 0 ... 0 0 0]
gestures\6\1152.jpg
[0 0 0 ... 0 0 0]
gestures\6\1153.jpg
[0 0 0 ... 0 0 0]
gestures\6\1154.jpg
[0 0 0 ... 0 0 0]
gestures\6\1155.jpg
[0 0 0 ... 0 0 0]
gestures\6\1156.jpg
[0 0 0 ... 0 0 0]
gestures\6\1157.jpg
[0 0 0 ... 0 0 0]
gestures\6\1158.jpg
[0 0 0 ... 0 0 0]
gestures\6\1159.jpg
[0 0 0 ... 0 0 0]
gestures\6\116.jpg
[0 0 0 ... 0 0 0]
gestures\6\1160.jpg
[0 0 0 ... 0 0 0]
gestures\6\1161.jpg
[0 0 0 ... 0 0 0]
gestures\6\1162.jpg
[0 0 0 ... 0 0 0]
gestures\6\1163.jpg
[0 0 0 ... 0 0 0]
gestures\6\1164.jpg
[0 0 0 ... 0 0 0]
gestures\6\1165.jpg
[0 0 0 ... 0 0 0]
gestures\6\1166.jpg
[0 0 0 ... 0 0 0]
gestures\6\1167.jpg
[0 0 0 ... 0 0 0]
gestures\6\1168.jpg
[0 0 0 ... 0 0

[0 0 0 ... 0 0 0]
gestures\6\275.jpg
[0 0 0 ... 0 0 0]
gestures\6\276.jpg
[0 0 0 ... 0 0 0]
gestures\6\277.jpg
[0 0 0 ... 0 0 0]
gestures\6\278.jpg
[0 0 0 ... 0 0 0]
gestures\6\279.jpg
[0 0 0 ... 0 0 0]
gestures\6\28.jpg
[0 1 0 ... 0 0 0]
gestures\6\280.jpg
[0 0 0 ... 0 0 0]
gestures\6\281.jpg
[0 0 0 ... 0 0 0]
gestures\6\282.jpg
[0 0 0 ... 0 0 0]
gestures\6\283.jpg
[0 0 0 ... 0 0 0]
gestures\6\284.jpg
[0 0 0 ... 0 0 0]
gestures\6\285.jpg
[0 0 0 ... 0 0 0]
gestures\6\286.jpg
[0 0 0 ... 0 0 0]
gestures\6\287.jpg
[0 0 0 ... 0 0 0]
gestures\6\288.jpg
[0 0 0 ... 0 0 0]
gestures\6\289.jpg
[0 0 0 ... 0 0 0]
gestures\6\29.jpg
[0 0 0 ... 0 0 0]
gestures\6\290.jpg
[0 0 0 ... 0 0 0]
gestures\6\291.jpg
[0 0 0 ... 0 0 0]
gestures\6\292.jpg
[0 0 0 ... 0 0 0]
gestures\6\293.jpg
[0 0 0 ... 0 0 0]
gestures\6\294.jpg
[0 0 0 ... 0 0 0]
gestures\6\295.jpg
[0 0 0 ... 0 0 0]
gestures\6\296.jpg
[0 0 0 ... 0 0 0]
gestures\6\297.jpg
[0 0 0 ... 0 0 0]
gestures\6\298.jpg
[0 0 0 ... 0 0 0]
gestures\6\299.jpg
[0 

gestures\6\48.jpg
[0 0 0 ... 0 0 0]
gestures\6\480.jpg
[0 0 0 ... 0 0 0]
gestures\6\481.jpg
[0 0 0 ... 0 0 0]
gestures\6\482.jpg
[0 0 0 ... 0 0 0]
gestures\6\483.jpg
[0 0 0 ... 0 0 0]
gestures\6\484.jpg
[0 0 0 ... 0 0 0]
gestures\6\485.jpg
[0 0 0 ... 0 0 0]
gestures\6\486.jpg
[0 0 0 ... 0 0 0]
gestures\6\487.jpg
[0 0 0 ... 0 0 0]
gestures\6\488.jpg
[0 0 0 ... 0 0 0]
gestures\6\489.jpg
[0 0 0 ... 0 0 0]
gestures\6\49.jpg
[0 0 0 ... 0 0 0]
gestures\6\490.jpg
[0 0 0 ... 0 0 0]
gestures\6\491.jpg
[0 0 0 ... 0 0 0]
gestures\6\492.jpg
[0 0 0 ... 0 0 0]
gestures\6\493.jpg
[0 0 0 ... 0 0 0]
gestures\6\494.jpg
[0 0 0 ... 0 0 0]
gestures\6\495.jpg
[0 0 0 ... 0 0 0]
gestures\6\496.jpg
[0 0 0 ... 0 0 0]
gestures\6\497.jpg
[0 0 0 ... 0 0 0]
gestures\6\498.jpg
[0 0 0 ... 0 0 0]
gestures\6\499.jpg
[0 0 0 ... 0 0 0]
gestures\6\5.jpg
[0 0 0 ... 0 0 0]
gestures\6\50.jpg
[0 0 0 ... 0 0 0]
gestures\6\500.jpg
[0 0 0 ... 0 0 0]
gestures\6\501.jpg
[0 0 0 ... 0 0 0]
gestures\6\502.jpg
[0 0 0 ... 0 0 0]
gestur

[0 0 0 ... 0 0 0]
gestures\6\700.jpg
[0 0 0 ... 0 0 0]
gestures\6\701.jpg
[0 0 0 ... 0 0 0]
gestures\6\702.jpg
[0 0 0 ... 0 0 0]
gestures\6\703.jpg
[0 0 0 ... 0 0 0]
gestures\6\704.jpg
[0 0 0 ... 0 0 0]
gestures\6\705.jpg
[0 0 0 ... 0 0 0]
gestures\6\706.jpg
[0 0 0 ... 0 0 0]
gestures\6\707.jpg
[0 0 0 ... 0 0 0]
gestures\6\708.jpg
[0 0 0 ... 0 0 0]
gestures\6\709.jpg
[0 0 0 ... 0 0 0]
gestures\6\71.jpg
[0 0 0 ... 0 0 0]
gestures\6\710.jpg
[0 0 0 ... 0 0 0]
gestures\6\711.jpg
[0 0 0 ... 0 0 0]
gestures\6\712.jpg
[0 0 0 ... 0 0 0]
gestures\6\713.jpg
[0 0 0 ... 0 0 0]
gestures\6\714.jpg
[0 0 0 ... 0 0 0]
gestures\6\715.jpg
[0 0 0 ... 0 0 0]
gestures\6\716.jpg
[0 0 0 ... 0 0 0]
gestures\6\717.jpg
[0 0 0 ... 0 0 0]
gestures\6\718.jpg
[0 0 0 ... 0 0 0]
gestures\6\719.jpg
[0 0 0 ... 0 0 0]
gestures\6\72.jpg
[0 0 0 ... 0 0 0]
gestures\6\720.jpg
[0 0 0 ... 0 0 0]
gestures\6\721.jpg
[0 0 0 ... 0 0 0]
gestures\6\722.jpg
[0 0 0 ... 0 0 0]
gestures\6\723.jpg
[0 0 0 ... 0 0 0]
gestures\6\724.jpg
[0 

gestures\6\924.jpg
[0 0 0 ... 0 0 0]
gestures\6\925.jpg
[0 0 0 ... 0 0 0]
gestures\6\926.jpg
[0 0 0 ... 0 0 0]
gestures\6\927.jpg
[0 0 0 ... 0 0 0]
gestures\6\928.jpg
[0 0 0 ... 0 0 0]
gestures\6\929.jpg
[0 0 0 ... 0 0 0]
gestures\6\93.jpg
[0 0 0 ... 0 0 0]
gestures\6\930.jpg
[0 0 0 ... 0 0 0]
gestures\6\931.jpg
[0 0 0 ... 0 0 0]
gestures\6\932.jpg
[0 0 0 ... 0 0 0]
gestures\6\933.jpg
[0 0 0 ... 0 0 0]
gestures\6\934.jpg
[0 0 0 ... 0 0 0]
gestures\6\935.jpg
[0 0 0 ... 0 0 0]
gestures\6\936.jpg
[0 0 0 ... 0 0 0]
gestures\6\937.jpg
[0 0 0 ... 0 0 0]
gestures\6\938.jpg
[0 0 0 ... 0 0 0]
gestures\6\939.jpg
[0 0 0 ... 0 0 0]
gestures\6\94.jpg
[0 0 0 ... 0 0 0]
gestures\6\940.jpg
[0 0 0 ... 0 0 0]
gestures\6\941.jpg
[0 0 0 ... 0 0 0]
gestures\6\942.jpg
[0 0 0 ... 0 0 0]
gestures\6\943.jpg
[0 0 0 ... 0 0 0]
gestures\6\944.jpg
[0 0 0 ... 0 0 0]
gestures\6\945.jpg
[0 0 0 ... 0 0 0]
gestures\6\946.jpg
[0 0 0 ... 0 0 0]
gestures\6\947.jpg
[0 0 0 ... 0 0 0]
gestures\6\948.jpg
[0 0 0 ... 0 0 0]
ges

gestures\7\1136.jpg
[0 0 0 ... 0 0 0]
gestures\7\1137.jpg
[0 0 0 ... 0 0 0]
gestures\7\1138.jpg
[0 0 0 ... 0 0 0]
gestures\7\1139.jpg
[0 0 0 ... 0 0 0]
gestures\7\114.jpg
[0 0 0 ... 0 0 0]
gestures\7\1140.jpg
[0 0 0 ... 0 0 0]
gestures\7\1141.jpg
[0 0 0 ... 0 0 0]
gestures\7\1142.jpg
[0 0 0 ... 0 0 0]
gestures\7\1143.jpg
[0 0 0 ... 0 0 0]
gestures\7\1144.jpg
[0 0 0 ... 0 0 0]
gestures\7\1145.jpg
[0 0 0 ... 2 0 0]
gestures\7\1146.jpg
[0 0 0 ... 0 0 0]
gestures\7\1147.jpg
[0 0 0 ... 0 0 0]
gestures\7\1148.jpg
[0 0 0 ... 0 0 0]
gestures\7\1149.jpg
[0 0 0 ... 0 0 0]
gestures\7\115.jpg
[0 0 0 ... 1 0 0]
gestures\7\1150.jpg
[0 0 0 ... 0 0 0]
gestures\7\1151.jpg
[0 0 0 ... 1 0 0]
gestures\7\1152.jpg
[0 0 0 ... 0 0 0]
gestures\7\1153.jpg
[0 0 0 ... 0 0 0]
gestures\7\1154.jpg
[0 0 0 ... 0 0 0]
gestures\7\1155.jpg
[0 0 0 ... 0 0 0]
gestures\7\1156.jpg
[0 0 0 ... 0 0 0]
gestures\7\1157.jpg
[0 0 0 ... 0 0 0]
gestures\7\1158.jpg
[0 0 0 ... 0 0 0]
gestures\7\1159.jpg
[0 0 0 ... 0 0 0]
gestures\7\116

gestures\7\260.jpg
[0 0 0 ... 0 0 0]
gestures\7\261.jpg
[0 0 0 ... 0 0 0]
gestures\7\262.jpg
[0 0 0 ... 0 0 0]
gestures\7\263.jpg
[0 0 0 ... 0 0 0]
gestures\7\264.jpg
[0 0 0 ... 0 0 0]
gestures\7\265.jpg
[0 0 0 ... 0 0 0]
gestures\7\266.jpg
[0 0 0 ... 0 0 0]
gestures\7\267.jpg
[0 0 0 ... 0 0 0]
gestures\7\268.jpg
[0 0 0 ... 0 0 0]
gestures\7\269.jpg
[0 0 0 ... 0 0 0]
gestures\7\27.jpg
[0 0 0 ... 0 0 0]
gestures\7\270.jpg
[0 0 0 ... 0 0 0]
gestures\7\271.jpg
[0 0 0 ... 0 0 0]
gestures\7\272.jpg
[0 0 0 ... 0 0 0]
gestures\7\273.jpg
[0 0 0 ... 0 0 0]
gestures\7\274.jpg
[0 0 0 ... 0 0 0]
gestures\7\275.jpg
[0 0 0 ... 0 0 0]
gestures\7\276.jpg
[0 0 0 ... 0 0 0]
gestures\7\277.jpg
[0 0 0 ... 0 0 0]
gestures\7\278.jpg
[0 0 0 ... 0 0 0]
gestures\7\279.jpg
[0 0 0 ... 0 0 0]
gestures\7\28.jpg
[0 0 0 ... 0 0 0]
gestures\7\280.jpg
[0 0 0 ... 0 0 0]
gestures\7\281.jpg
[0 0 0 ... 0 0 0]
gestures\7\282.jpg
[0 0 0 ... 0 0 0]
gestures\7\283.jpg
[0 0 0 ... 0 0 0]
gestures\7\284.jpg
[0 0 0 ... 0 0 0]
ges

[0 0 0 ... 0 0 0]
gestures\7\473.jpg
[0 0 0 ... 0 0 0]
gestures\7\474.jpg
[0 0 0 ... 0 0 0]
gestures\7\475.jpg
[0 0 0 ... 0 0 0]
gestures\7\476.jpg
[0 0 0 ... 1 0 0]
gestures\7\477.jpg
[0 0 0 ... 0 0 0]
gestures\7\478.jpg
[0 0 0 ... 0 0 0]
gestures\7\479.jpg
[0 0 0 ... 0 0 0]
gestures\7\48.jpg
[0 0 0 ... 0 0 0]
gestures\7\480.jpg
[0 0 0 ... 0 0 0]
gestures\7\481.jpg
[0 0 0 ... 0 0 0]
gestures\7\482.jpg
[0 0 0 ... 1 0 0]
gestures\7\483.jpg
[0 0 0 ... 0 0 0]
gestures\7\484.jpg
[0 0 0 ... 0 0 0]
gestures\7\485.jpg
[0 0 0 ... 0 0 0]
gestures\7\486.jpg
[0 0 0 ... 0 0 0]
gestures\7\487.jpg
[0 0 0 ... 0 0 0]
gestures\7\488.jpg
[0 0 0 ... 0 0 0]
gestures\7\489.jpg
[0 0 0 ... 0 0 0]
gestures\7\49.jpg
[0 0 0 ... 0 0 0]
gestures\7\490.jpg
[0 0 0 ... 0 0 0]
gestures\7\491.jpg
[0 0 0 ... 0 0 0]
gestures\7\492.jpg
[0 0 0 ... 0 0 0]
gestures\7\493.jpg
[0 0 0 ... 0 0 0]
gestures\7\494.jpg
[0 0 0 ... 0 0 0]
gestures\7\495.jpg
[0 0 0 ... 0 0 0]
gestures\7\496.jpg
[0 0 0 ... 0 0 0]
gestures\7\497.jpg
[0 

[0 0 0 ... 0 0 0]
gestures\7\680.jpg
[0 0 0 ... 0 0 0]
gestures\7\681.jpg
[0 0 0 ... 0 0 0]
gestures\7\682.jpg
[0 0 0 ... 0 0 0]
gestures\7\683.jpg
[0 0 0 ... 0 0 0]
gestures\7\684.jpg
[0 0 0 ... 0 0 0]
gestures\7\685.jpg
[0 0 0 ... 0 0 0]
gestures\7\686.jpg
[0 0 0 ... 0 0 0]
gestures\7\687.jpg
[0 0 0 ... 0 0 0]
gestures\7\688.jpg
[0 0 0 ... 0 0 0]
gestures\7\689.jpg
[0 0 0 ... 1 0 0]
gestures\7\69.jpg
[0 0 0 ... 0 0 0]
gestures\7\690.jpg
[0 0 0 ... 0 0 0]
gestures\7\691.jpg
[0 0 0 ... 0 0 0]
gestures\7\692.jpg
[0 0 0 ... 0 0 0]
gestures\7\693.jpg
[0 0 0 ... 0 0 0]
gestures\7\694.jpg
[0 0 0 ... 0 0 0]
gestures\7\695.jpg
[0 0 0 ... 0 0 0]
gestures\7\696.jpg
[0 0 0 ... 1 0 0]
gestures\7\697.jpg
[0 0 0 ... 0 0 0]
gestures\7\698.jpg
[0 0 0 ... 0 0 0]
gestures\7\699.jpg
[0 0 0 ... 0 0 0]
gestures\7\7.jpg
[0 0 0 ... 0 0 0]
gestures\7\70.jpg
[0 0 0 ... 0 0 0]
gestures\7\700.jpg
[0 0 0 ... 0 0 0]
gestures\7\701.jpg
[0 0 0 ... 0 0 0]
gestures\7\702.jpg
[0 0 0 ... 0 0 0]
gestures\7\703.jpg
[0 0 

gestures\7\886.jpg
[0 0 0 ... 0 0 0]
gestures\7\887.jpg
[0 0 0 ... 2 0 0]
gestures\7\888.jpg
[0 0 0 ... 0 0 0]
gestures\7\889.jpg
[0 0 0 ... 0 0 0]
gestures\7\89.jpg
[0 0 0 ... 0 0 0]
gestures\7\890.jpg
[0 0 0 ... 0 0 0]
gestures\7\891.jpg
[0 0 0 ... 0 0 0]
gestures\7\892.jpg
[0 0 0 ... 0 0 0]
gestures\7\893.jpg
[0 0 0 ... 0 0 0]
gestures\7\894.jpg
[0 0 0 ... 0 0 0]
gestures\7\895.jpg
[0 0 0 ... 0 0 0]
gestures\7\896.jpg
[0 0 0 ... 0 0 0]
gestures\7\897.jpg
[0 0 0 ... 0 0 0]
gestures\7\898.jpg
[0 0 0 ... 0 0 0]
gestures\7\899.jpg
[0 0 0 ... 0 0 0]
gestures\7\9.jpg
[0 0 0 ... 0 0 0]
gestures\7\90.jpg
[0 0 0 ... 0 0 0]
gestures\7\900.jpg
[0 0 0 ... 0 0 0]
gestures\7\901.jpg
[0 0 0 ... 0 0 0]
gestures\7\902.jpg
[0 0 0 ... 0 0 0]
gestures\7\903.jpg
[0 0 0 ... 2 0 0]
gestures\7\904.jpg
[0 0 0 ... 0 0 0]
gestures\7\905.jpg
[0 0 0 ... 0 0 0]
gestures\7\906.jpg
[0 0 0 ... 0 0 0]
gestures\7\907.jpg
[0 0 0 ... 0 0 0]
gestures\7\908.jpg
[0 0 0 ... 0 0 0]
gestures\7\909.jpg
[0 0 0 ... 0 0 0]
gestu

[0 0 0 ... 0 0 0]
gestures\8\1085.jpg
[0 0 0 ... 0 0 0]
gestures\8\1086.jpg
[0 0 0 ... 0 0 0]
gestures\8\1087.jpg
[0 0 0 ... 0 0 0]
gestures\8\1088.jpg
[0 0 0 ... 0 0 0]
gestures\8\1089.jpg
[0 0 0 ... 0 0 0]
gestures\8\109.jpg
[0 0 0 ... 0 0 0]
gestures\8\1090.jpg
[0 0 0 ... 0 0 0]
gestures\8\1091.jpg
[0 0 0 ... 0 0 0]
gestures\8\1092.jpg
[0 0 0 ... 0 0 0]
gestures\8\1093.jpg
[0 0 0 ... 0 0 0]
gestures\8\1094.jpg
[0 0 0 ... 0 0 0]
gestures\8\1095.jpg
[0 0 0 ... 0 0 0]
gestures\8\1096.jpg
[0 0 0 ... 0 0 0]
gestures\8\1097.jpg
[0 0 0 ... 0 0 0]
gestures\8\1098.jpg
[0 0 0 ... 0 0 0]
gestures\8\1099.jpg
[0 0 0 ... 0 0 0]
gestures\8\11.jpg
[0 0 0 ... 0 0 0]
gestures\8\110.jpg
[0 0 0 ... 0 0 0]
gestures\8\1100.jpg
[0 0 0 ... 0 0 0]
gestures\8\1101.jpg
[0 0 0 ... 0 0 0]
gestures\8\1102.jpg
[0 0 0 ... 0 0 0]
gestures\8\1103.jpg
[0 0 0 ... 0 0 0]
gestures\8\1104.jpg
[0 0 0 ... 0 0 0]
gestures\8\1105.jpg
[0 0 0 ... 0 0 0]
gestures\8\1106.jpg
[0 0 0 ... 0 0 0]
gestures\8\1107.jpg
[0 0 0 ... 0 0 0

[0 0 0 ... 0 0 0]
gestures\8\235.jpg
[0 0 0 ... 0 0 0]
gestures\8\236.jpg
[0 0 0 ... 0 0 0]
gestures\8\237.jpg
[0 0 0 ... 0 0 0]
gestures\8\238.jpg
[0 0 0 ... 0 0 0]
gestures\8\239.jpg
[0 0 0 ... 0 0 0]
gestures\8\24.jpg
[0 0 0 ... 0 0 0]
gestures\8\240.jpg
[0 0 0 ... 0 0 0]
gestures\8\241.jpg
[0 0 0 ... 0 0 0]
gestures\8\242.jpg
[0 0 0 ... 0 0 0]
gestures\8\243.jpg
[0 0 0 ... 0 0 0]
gestures\8\244.jpg
[0 0 0 ... 0 0 0]
gestures\8\245.jpg
[0 0 0 ... 0 0 0]
gestures\8\246.jpg
[0 0 0 ... 0 0 0]
gestures\8\247.jpg
[0 0 0 ... 0 0 0]
gestures\8\248.jpg
[0 0 0 ... 0 0 0]
gestures\8\249.jpg
[0 0 0 ... 0 0 0]
gestures\8\25.jpg
[0 0 0 ... 0 0 0]
gestures\8\250.jpg
[0 0 0 ... 0 0 0]
gestures\8\251.jpg
[0 0 0 ... 0 0 0]
gestures\8\252.jpg
[0 0 0 ... 0 0 0]
gestures\8\253.jpg
[0 0 0 ... 0 0 0]
gestures\8\254.jpg
[0 0 0 ... 0 0 0]
gestures\8\255.jpg
[0 0 0 ... 0 0 0]
gestures\8\256.jpg
[0 0 0 ... 0 0 0]
gestures\8\257.jpg
[0 0 0 ... 0 0 0]
gestures\8\258.jpg
[0 0 0 ... 0 0 0]
gestures\8\259.jpg
[0 

gestures\8\438.jpg
[0 0 0 ... 0 0 0]
gestures\8\439.jpg
[0 0 0 ... 0 0 0]
gestures\8\44.jpg
[0 0 0 ... 0 0 0]
gestures\8\440.jpg
[0 0 0 ... 0 0 0]
gestures\8\441.jpg
[0 0 0 ... 0 0 0]
gestures\8\442.jpg
[0 0 0 ... 0 0 0]
gestures\8\443.jpg
[0 0 0 ... 0 0 0]
gestures\8\444.jpg
[0 0 0 ... 0 0 0]
gestures\8\445.jpg
[0 0 0 ... 0 0 0]
gestures\8\446.jpg
[0 0 0 ... 0 0 0]
gestures\8\447.jpg
[0 0 0 ... 0 0 0]
gestures\8\448.jpg
[0 0 0 ... 0 0 0]
gestures\8\449.jpg
[0 0 0 ... 0 0 0]
gestures\8\45.jpg
[0 0 0 ... 0 0 0]
gestures\8\450.jpg
[0 0 0 ... 0 0 0]
gestures\8\451.jpg
[0 0 0 ... 0 0 0]
gestures\8\452.jpg
[0 0 0 ... 0 0 0]
gestures\8\453.jpg
[0 0 0 ... 0 0 0]
gestures\8\454.jpg
[0 0 0 ... 0 0 0]
gestures\8\455.jpg
[0 0 0 ... 0 0 0]
gestures\8\456.jpg
[0 0 0 ... 0 0 0]
gestures\8\457.jpg
[0 0 0 ... 0 0 0]
gestures\8\458.jpg
[0 0 0 ... 0 0 0]
gestures\8\459.jpg
[0 0 0 ... 0 0 0]
gestures\8\46.jpg
[0 0 0 ... 0 0 0]
gestures\8\460.jpg
[0 0 0 ... 0 0 0]
gestures\8\461.jpg
[0 0 0 ... 0 0 0]
gest

[0 0 0 ... 0 0 0]
gestures\8\652.jpg
[0 0 0 ... 0 0 0]
gestures\8\653.jpg
[0 0 0 ... 0 0 0]
gestures\8\654.jpg
[0 0 0 ... 0 0 0]
gestures\8\655.jpg
[0 0 0 ... 0 0 0]
gestures\8\656.jpg
[0 0 0 ... 0 0 0]
gestures\8\657.jpg
[0 0 0 ... 0 0 0]
gestures\8\658.jpg
[0 0 0 ... 0 0 0]
gestures\8\659.jpg
[0 0 0 ... 0 0 0]
gestures\8\66.jpg
[0 0 0 ... 0 0 0]
gestures\8\660.jpg
[0 0 0 ... 0 0 0]
gestures\8\661.jpg
[0 0 0 ... 0 0 0]
gestures\8\662.jpg
[0 0 0 ... 0 0 0]
gestures\8\663.jpg
[0 0 0 ... 0 0 0]
gestures\8\664.jpg
[0 0 0 ... 0 0 0]
gestures\8\665.jpg
[0 0 0 ... 0 0 0]
gestures\8\666.jpg
[0 0 0 ... 0 0 0]
gestures\8\667.jpg
[0 0 0 ... 0 0 0]
gestures\8\668.jpg
[0 0 0 ... 0 0 0]
gestures\8\669.jpg
[0 0 0 ... 0 0 0]
gestures\8\67.jpg
[0 0 0 ... 0 0 0]
gestures\8\670.jpg
[0 0 0 ... 0 0 0]
gestures\8\671.jpg
[0 0 0 ... 0 0 0]
gestures\8\672.jpg
[0 0 0 ... 0 0 0]
gestures\8\673.jpg
[0 0 0 ... 0 0 0]
gestures\8\674.jpg
[0 0 0 ... 0 0 0]
gestures\8\675.jpg
[0 0 0 ... 0 0 0]
gestures\8\676.jpg
[0 

gestures\8\861.jpg
[0 0 0 ... 0 0 0]
gestures\8\862.jpg
[0 0 0 ... 0 0 0]
gestures\8\863.jpg
[0 0 0 ... 0 0 0]
gestures\8\864.jpg
[0 0 0 ... 0 0 0]
gestures\8\865.jpg
[0 0 0 ... 0 0 0]
gestures\8\866.jpg
[0 0 0 ... 0 0 0]
gestures\8\867.jpg
[0 0 0 ... 0 0 0]
gestures\8\868.jpg
[0 0 0 ... 0 0 0]
gestures\8\869.jpg
[0 0 0 ... 0 0 0]
gestures\8\87.jpg
[0 0 0 ... 0 0 0]
gestures\8\870.jpg
[0 0 0 ... 0 0 0]
gestures\8\871.jpg
[0 0 0 ... 0 0 0]
gestures\8\872.jpg
[0 0 0 ... 0 0 0]
gestures\8\873.jpg
[0 0 0 ... 0 0 0]
gestures\8\874.jpg
[0 0 0 ... 0 0 0]
gestures\8\875.jpg
[0 0 0 ... 0 0 0]
gestures\8\876.jpg
[0 0 0 ... 0 0 0]
gestures\8\877.jpg
[0 0 0 ... 0 0 0]
gestures\8\878.jpg
[0 0 0 ... 0 0 0]
gestures\8\879.jpg
[0 0 0 ... 0 0 0]
gestures\8\88.jpg
[0 0 0 ... 0 0 0]
gestures\8\880.jpg
[0 0 0 ... 0 0 0]
gestures\8\881.jpg
[0 0 0 ... 0 0 0]
gestures\8\882.jpg
[0 0 0 ... 0 0 0]
gestures\8\883.jpg
[0 0 0 ... 0 0 0]
gestures\8\884.jpg
[0 0 0 ... 0 0 0]
gestures\8\885.jpg
[0 0 0 ... 0 0 0]
ges

gestures\9\107.jpg
[0 0 0 ... 0 0 0]
gestures\9\1070.jpg
[0 0 0 ... 0 0 0]
gestures\9\1071.jpg
[0 0 0 ... 0 0 0]
gestures\9\1072.jpg
[0 0 0 ... 0 0 0]
gestures\9\1073.jpg
[0 0 0 ... 0 0 0]
gestures\9\1074.jpg
[0 0 0 ... 0 0 0]
gestures\9\1075.jpg
[0 0 0 ... 0 0 0]
gestures\9\1076.jpg
[0 0 0 ... 0 0 0]
gestures\9\1077.jpg
[0 0 0 ... 0 0 0]
gestures\9\1078.jpg
[0 0 0 ... 0 0 0]
gestures\9\1079.jpg
[0 0 0 ... 0 0 0]
gestures\9\108.jpg
[0 0 0 ... 0 0 0]
gestures\9\1080.jpg
[0 0 0 ... 0 0 0]
gestures\9\1081.jpg
[0 0 0 ... 0 0 0]
gestures\9\1082.jpg
[0 0 0 ... 0 0 0]
gestures\9\1083.jpg
[0 0 0 ... 0 0 0]
gestures\9\1084.jpg
[0 0 0 ... 0 0 0]
gestures\9\1085.jpg
[0 0 0 ... 0 0 0]
gestures\9\1086.jpg
[0 0 0 ... 0 0 0]
gestures\9\1087.jpg
[0 0 0 ... 0 0 0]
gestures\9\1088.jpg
[0 0 0 ... 0 0 0]
gestures\9\1089.jpg
[0 0 0 ... 0 0 0]
gestures\9\109.jpg
[0 0 0 ... 0 0 0]
gestures\9\1090.jpg
[0 0 0 ... 0 0 0]
gestures\9\1091.jpg
[0 0 0 ... 0 0 0]
gestures\9\1092.jpg
[0 0 0 ... 0 0 0]
gestures\9\1093

[0 0 0 ... 0 0 0]
gestures\9\210.jpg
[0 0 0 ... 0 0 0]
gestures\9\211.jpg
[0 0 0 ... 0 0 0]
gestures\9\212.jpg
[0 0 0 ... 0 0 0]
gestures\9\213.jpg
[0 0 0 ... 0 0 0]
gestures\9\214.jpg
[0 0 0 ... 0 0 0]
gestures\9\215.jpg
[0 0 0 ... 0 0 0]
gestures\9\216.jpg
[0 0 0 ... 0 0 0]
gestures\9\217.jpg
[0 0 0 ... 0 0 0]
gestures\9\218.jpg
[0 0 0 ... 0 0 0]
gestures\9\219.jpg
[0 0 0 ... 0 0 0]
gestures\9\22.jpg
[0 0 0 ... 0 0 0]
gestures\9\220.jpg
[0 0 0 ... 0 0 0]
gestures\9\221.jpg
[0 0 0 ... 0 0 0]
gestures\9\222.jpg
[0 0 0 ... 0 0 0]
gestures\9\223.jpg
[0 0 0 ... 0 0 0]
gestures\9\224.jpg
[0 0 0 ... 0 0 0]
gestures\9\225.jpg
[0 0 0 ... 0 0 0]
gestures\9\226.jpg
[0 0 0 ... 0 0 0]
gestures\9\227.jpg
[0 0 0 ... 0 0 0]
gestures\9\228.jpg
[0 0 0 ... 0 0 0]
gestures\9\229.jpg
[0 0 0 ... 0 0 0]
gestures\9\23.jpg
[0 0 0 ... 0 0 0]
gestures\9\230.jpg
[0 0 0 ... 0 0 0]
gestures\9\231.jpg
[0 0 0 ... 0 0 0]
gestures\9\232.jpg
[0 0 0 ... 0 0 0]
gestures\9\233.jpg
[0 0 0 ... 0 0 0]
gestures\9\234.jpg
[0 

gestures\9\443.jpg
[0 0 0 ... 0 0 0]
gestures\9\444.jpg
[0 0 0 ... 0 0 0]
gestures\9\445.jpg
[0 0 0 ... 0 0 0]
gestures\9\446.jpg
[0 0 0 ... 0 0 0]
gestures\9\447.jpg
[0 0 0 ... 0 0 0]
gestures\9\448.jpg
[0 0 0 ... 0 0 0]
gestures\9\449.jpg
[0 0 0 ... 0 0 0]
gestures\9\45.jpg
[0 0 0 ... 0 0 0]
gestures\9\450.jpg
[0 0 0 ... 0 0 0]
gestures\9\451.jpg
[0 0 0 ... 0 0 0]
gestures\9\452.jpg
[0 0 0 ... 0 0 0]
gestures\9\453.jpg
[0 0 0 ... 0 0 0]
gestures\9\454.jpg
[0 0 0 ... 0 0 0]
gestures\9\455.jpg
[0 0 0 ... 0 0 0]
gestures\9\456.jpg
[0 0 0 ... 0 0 0]
gestures\9\457.jpg
[0 0 0 ... 0 0 0]
gestures\9\458.jpg
[0 0 0 ... 0 0 0]
gestures\9\459.jpg
[0 0 0 ... 0 0 0]
gestures\9\46.jpg
[0 1 1 ... 0 0 0]
gestures\9\460.jpg
[0 0 0 ... 0 0 0]
gestures\9\461.jpg
[0 0 0 ... 0 0 0]
gestures\9\462.jpg
[0 0 0 ... 0 0 0]
gestures\9\463.jpg
[0 0 0 ... 0 0 0]
gestures\9\464.jpg
[0 0 0 ... 0 0 0]
gestures\9\465.jpg
[0 0 0 ... 0 0 0]
gestures\9\466.jpg
[0 0 0 ... 0 0 0]
gestures\9\467.jpg
[0 0 0 ... 0 0 0]
ges

[0 0 0 ... 0 0 0]
gestures\9\659.jpg
[0 0 0 ... 0 0 0]
gestures\9\66.jpg
[0 0 0 ... 0 0 0]
gestures\9\660.jpg
[0 0 0 ... 0 0 0]
gestures\9\661.jpg
[0 0 0 ... 0 0 0]
gestures\9\662.jpg
[0 0 0 ... 0 0 0]
gestures\9\663.jpg
[0 0 0 ... 0 0 0]
gestures\9\664.jpg
[0 0 0 ... 0 0 0]
gestures\9\665.jpg
[0 0 0 ... 0 0 0]
gestures\9\666.jpg
[0 0 0 ... 0 0 0]
gestures\9\667.jpg
[0 0 0 ... 0 0 0]
gestures\9\668.jpg
[0 0 0 ... 0 0 0]
gestures\9\669.jpg
[0 0 0 ... 0 0 0]
gestures\9\67.jpg
[0 0 0 ... 0 0 0]
gestures\9\670.jpg
[0 0 0 ... 0 0 0]
gestures\9\671.jpg
[0 0 0 ... 0 0 0]
gestures\9\672.jpg
[0 0 0 ... 0 0 0]
gestures\9\673.jpg
[0 0 0 ... 0 0 0]
gestures\9\674.jpg
[0 0 0 ... 0 0 0]
gestures\9\675.jpg
[0 0 0 ... 0 0 0]
gestures\9\676.jpg
[0 0 0 ... 0 0 0]
gestures\9\677.jpg
[0 0 0 ... 0 0 0]
gestures\9\678.jpg
[0 0 0 ... 0 0 0]
gestures\9\679.jpg
[0 0 0 ... 0 0 0]
gestures\9\68.jpg
[0 0 0 ... 0 0 0]
gestures\9\680.jpg
[0 0 0 ... 0 0 0]
gestures\9\681.jpg
[0 0 0 ... 0 0 0]
gestures\9\682.jpg
[0 0

gestures\9\88.jpg
[0 0 0 ... 0 0 0]
gestures\9\880.jpg
[0 0 0 ... 0 0 0]
gestures\9\881.jpg
[0 0 0 ... 0 0 0]
gestures\9\882.jpg
[0 0 0 ... 0 0 0]
gestures\9\883.jpg
[0 0 0 ... 0 0 0]
gestures\9\884.jpg
[0 0 0 ... 0 0 0]
gestures\9\885.jpg
[0 0 0 ... 0 0 0]
gestures\9\886.jpg
[0 0 0 ... 0 0 0]
gestures\9\887.jpg
[0 0 0 ... 0 0 0]
gestures\9\888.jpg
[0 0 0 ... 0 0 0]
gestures\9\889.jpg
[0 0 0 ... 0 0 0]
gestures\9\89.jpg
[0 0 0 ... 0 0 0]
gestures\9\890.jpg
[0 0 0 ... 0 0 0]
gestures\9\891.jpg
[0 0 0 ... 0 0 0]
gestures\9\892.jpg
[0 0 0 ... 0 0 0]
gestures\9\893.jpg
[0 0 0 ... 0 0 0]
gestures\9\894.jpg
[0 0 0 ... 0 0 0]
gestures\9\895.jpg
[0 0 0 ... 0 0 0]
gestures\9\896.jpg
[0 0 0 ... 0 0 0]
gestures\9\897.jpg
[0 0 0 ... 0 0 0]
gestures\9\898.jpg
[0 0 0 ... 0 0 0]
gestures\9\899.jpg
[0 0 0 ... 0 0 0]
gestures\9\9.jpg
[0 0 0 ... 0 0 0]
gestures\9\90.jpg
[0 0 0 ... 0 0 0]
gestures\9\900.jpg
[0 0 0 ... 0 0 0]
gestures\9\901.jpg
[0 0 0 ... 0 0 0]
gestures\9\902.jpg
[0 0 0 ... 0 0 0]
gestur